/**
 * Datos del quiz de Empresa e Iniciativa Emprendedora - El Estudio de Mercado
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "¿Qué es una necesidad desde el punto de vista del mercado?",
        a: "La cantidad de producto que los vendedores están dispuestos a ofrecer",
        b: "El lugar donde se realizan intercambios comerciales",
        c: "Insatisfacción producida por no tener algo",
        d: "El conjunto de técnicas para conseguir ventas",
        correct: "c",
    },
    {
        question: "¿Qué es la demanda?",
        a: "Insatisfacción producida por no tener algo",
        b: "Cantidad de producto que los compradores están dispuestos a adquirir a un determinado precio",
        c: "Cantidad de producto que los vendedores están dispuestos a ofrecer",
        d: "El conjunto de compradores y vendedores de un producto",
        correct: "b",
    },
    {
        question: "¿Qué es la oferta?",
        a: "Cantidad de producto que los vendedores están dispuestos a ofrecer a un determinado precio",
        b: "Cantidad de producto que los compradores están dispuestos a adquirir",
        c: "El lugar donde se realizan intercambios",
        d: "Un descuento especial en un producto",
        correct: "a",
    },
    {
        question: "¿Qué ocurre cuando aumenta el precio en la curva de oferta?",
        a: "Disminuye la cantidad ofertada",
        b: "Aumenta la cantidad ofertada",
        c: "La cantidad ofertada se mantiene estable",
        d: "La curva de oferta se desplaza hacia la izquierda",
        correct: "b",
    },
    {
        question: "¿Qué ocurre cuando aumenta el precio en la curva de demanda?",
        a: "Aumenta la cantidad demandada",
        b: "La cantidad demandada se mantiene estable",
        c: "Disminuye la cantidad demandada",
        d: "La curva de demanda se desplaza hacia la derecha",
        correct: "c",
    },
    {
        question: "¿Qué es el precio de mercado?",
        a: "El precio máximo que están dispuestos a pagar los consumidores",
        b: "El precio mínimo que aceptan los vendedores",
        c: "El precio que marca la situación de equilibrio entre oferta y demanda",
        d: "El precio fijado por el gobierno",
        correct: "c",
    },
    {
        question: "Si el precio de un producto es mayor que el precio de equilibrio, ¿qué situación se produce?",
        a: "Escasez de producto",
        b: "Exceso de oferta",
        c: "Exceso de demanda",
        d: "Inflación generalizada",
        correct: "b",
    },
    {
        question: "¿Qué es el tamaño de mercado de un producto?",
        a: "El número de empresas que venden el producto",
        b: "El espacio físico que ocupa el mercado",
        c: "La cantidad vendida durante un periodo determinado en un área geográfica concreta",
        d: "El número de productos diferentes disponibles",
        correct: "c",
    },
    {
        question: "¿Qué es el mercado potencial?",
        a: "Los compradores reales más los compradores potenciales",
        b: "Solo los compradores reales",
        c: "Solo los compradores potenciales",
        d: "El total de la población de un área",
        correct: "a",
    },
    {
        question: "¿Cómo se calcula la cuota de mercado?",
        a: "Ventas totales del mercado / Ventas de una empresa × 100",
        b: "Ventas de una empresa / Ventas totales del mercado × 100",
        c: "Beneficios de una empresa / Ventas de una empresa × 100",
        d: "Ventas de una empresa - Ventas de la competencia",
        correct: "b",
    },
    {
        question: "¿Qué tipo de mercado se caracteriza por tener un solo vendedor?",
        a: "Oligopolio",
        b: "Competencia perfecta",
        c: "Monopolio",
        d: "Competencia monopolística",
        correct: "c",
    },
    {
        question: "¿Qué tipo de mercado se caracteriza por tener pocos vendedores?",
        a: "Monopolio",
        b: "Oligopolio",
        c: "Competencia perfecta",
        d: "Monopsonio",
        correct: "b",
    },
    {
        question: "¿Qué tipo de mercado se caracteriza por tener muchos vendedores con productos diferenciados?",
        a: "Monopolio",
        b: "Oligopolio",
        c: "Competencia perfecta",
        d: "Competencia monopolística",
        correct: "d",
    },
    {
        question: "¿Qué tipo de mercado se caracteriza por tener muchos vendedores y un producto homogéneo?",
        a: "Monopolio",
        b: "Oligopolio",
        c: "Competencia perfecta",
        d: "Competencia monopolística",
        correct: "c",
    },
    {
        question: "¿Qué es la segmentación de mercado?",
        a: "Dividir el mercado en grupos de compradores con características similares",
        b: "Establecer diferentes precios según la zona geográfica",
        c: "Dividir la producción entre diferentes fábricas",
        d: "Separar a los clientes según su fidelidad a la marca",
        correct: "a",
    },
    {
        question: "¿Cuál de los siguientes NO es un criterio de segmentación de mercado?",
        a: "Geográfico",
        b: "Financiero",
        c: "Demográfico",
        d: "Psicológico",
        correct: "b",
    },
    {
        question: "¿Qué tipo de estrategia de segmentación se aplica cuando la empresa se dirige a todos los segmentos con el mismo producto?",
        a: "Diferenciada",
        b: "Indiferenciada",
        c: "Concentrada",
        d: "Personalizada",
        correct: "b",
    },
    {
        question: "¿Qué tipo de estrategia de segmentación se aplica cuando la empresa se centra en un solo segmento?",
        a: "Diferenciada",
        b: "Indiferenciada",
        c: "Concentrada",
        d: "Personalizada",
        correct: "c",
    },
    {
        question: "¿Para qué sirve un Empathy Map en el estudio de mercado?",
        a: "Para calcular el precio óptimo de venta",
        b: "Para entender mejor lo que piensa y siente el cliente potencial",
        c: "Para analizar a la competencia",
        d: "Para diseñar la estrategia de distribución",
        correct: "b",
    },
    {
        question: "Cuando el propietario recomienda el libro, el comprador es la familia y el usuario es el niño, ¿qué fenómeno se está dando en el caso de los libros de texto infantiles?",
        a: "Marketing directo",
        b: "Venta cruzada",
        c: "Diferentes roles en la decisión de compra",
        d: "Fidelización del cliente",
        correct: "c",
    },
    {
        question: "¿Qué es la competencia desde el punto de vista del mercado?",
        a: "Las habilidades profesionales de los trabajadores",
        b: "La concurrencia en el mismo mercado de distintos oferentes de bienes o servicios",
        c: "La capacidad de las empresas para fijar precios",
        d: "La rivalidad entre compradores",
        correct: "b",
    },
    {
        question: "¿Qué es la ventaja competitiva?",
        a: "El monopolio legal otorgado por el Estado",
        b: "La característica que nos diferencia positivamente de nuestra competencia",
        c: "El volumen de producción mayor que los competidores",
        d: "El número de años que lleva la empresa en el mercado",
        correct: "b",
    },
    {
        question: "¿Qué característica define a la estrategia del Océano Azul?",
        a: "Retar a la competencia en un mercado existente",
        b: "Explotar la demanda existente en el mercado",
        c: "Crear un espacio sin competencia en el mercado",
        d: "Alinear el sistema con la diferenciación o el bajo coste",
        correct: "c",
    },
    {
        question: "¿Qué característica define a la estrategia del Océano Rojo?",
        a: "Competir en el espacio existente del mercado",
        b: "Crear y captar demanda nueva",
        c: "Hacer que la competencia se torne irrelevante",
        d: "Romper la disyuntiva del valor o el coste",
        correct: "a",
    },
    {
        question: "¿Qué es el marketing mix?",
        a: "La mezcla de mercados donde opera una empresa",
        b: "El análisis y selección de los mercados a servir",
        c: "La estrategia de redes sociales de una empresa",
        d: "El conjunto de variables producto, precio, distribución y promoción",
        correct: "d",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}