/**
 * Datos del quiz de Empresa e Iniciativa Emprendedora - Costes y Aprovisionamiento
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "¿Qué criterios son relevantes para la selección de proveedores?",
        a: "Solo el precio",
        b: "Solo la calidad",
        c: "Exclusivamente el plazo de entrega",
        d: "Precio, calidad, descuentos, condiciones de pago, plazo de entrega y servicio post-venta",
        correct: "d",
    },
    {
        question: "¿Qué estrategia de negociación con proveedores se basa en la confianza mutua y cooperación?",
        a: "Yo Gano - Tú pierdes (Win-Lose)",
        b: "Yo Gano - Tú Ganas (Win-Win)",
        c: "Yo Pierdo - Tú Ganas",
        d: "Negociación autoritaria",
        correct: "b",
    },
    {
        question: "¿Qué consecuencia negativa tiene almacenar MÁS mercancía de la necesaria?",
        a: "No tener materia prima",
        b: "Mayor liquidez financiera",
        c: "Incremento de gastos (personal, instalaciones, seguros, dinero inmovilizado)",
        d: "Mejora de la productividad",
        correct: "c",
    },
    {
        question: "Según algunos autores, ¿qué porcentaje del valor de la mercancía supone el coste de almacenamiento?",
        a: "Entre un 5-10%",
        b: "Entre un 20-25%",
        c: "Entre un 40-50%",
        d: "Menos del 5%",
        correct: "b",
    },
    {
        question: "¿Qué empresas basan parte de su éxito en la gestión eficiente de inventarios?",
        a: "Toyota, Zara, LIDL, IKEA",
        b: "Solo empresas pequeñas",
        c: "Únicamente empresas de tecnología",
        d: "Empresas con productos de lujo",
        correct: "a",
    },
    {
        question: "¿Qué es el stock de seguridad?",
        a: "El nivel máximo de existencias que puede almacenar una empresa",
        b: "Existencias mínimas para poder hacer frente a pedidos imprevistos o retrasos de proveedores",
        c: "La mercancía defectuosa que se guarda por seguridad",
        d: "El inventario que se protege con sistemas de seguridad",
        correct: "b",
    },
    {
        question: "¿Qué es el punto de pedido?",
        a: "La cantidad mínima de mercancía que debe tener un proveedor",
        b: "El momento en que el proveedor nos envía la mercancía",
        c: "Nivel de stock llegado al cual debemos solicitar un nuevo pedido",
        d: "El lugar físico donde se realizan los pedidos",
        correct: "c",
    },
    {
        question: "Si un proveedor tarda 5 días en servir, la empresa consume 250 unidades diarias y el stock de seguridad es de 600 unidades, ¿cuál es el punto de pedido?",
        a: "1250 unidades",
        b: "1850 unidades",
        c: "600 unidades",
        d: "2450 unidades",
        correct: "b",
    },
    {
        question: "¿Cuál es el principio fundamental del sistema Just In Time (JIT)?",
        a: "Almacenar la mayor cantidad posible de mercancía",
        b: "El almacén debe ser lo más grande posible",
        c: "El almacén no debe existir o ser lo más pequeño posible",
        d: "Producir exclusivamente los fines de semana",
        correct: "c",
    },
    {
        question: "¿Cuáles son las condiciones necesarias para implementar un sistema Just In Time?",
        a: "Solo se necesita calidad perfecta",
        b: "Calidad perfecta, alta flexibilidad y proveedores con sistema JIT",
        c: "Únicamente alta flexibilidad",
        d: "Mano de obra muy barata",
        correct: "b",
    },
    {
        question: "¿Qué son los costes fijos?",
        a: "Costes que varían con el volumen de producción",
        b: "Costes que no varían con el volumen de producción",
        c: "Costes relacionados exclusivamente con la materia prima",
        d: "Costes que solo se pagan una vez al año",
        correct: "b",
    },
    {
        question: "¿Cuál de los siguientes es un ejemplo de coste fijo?",
        a: "Materias primas",
        b: "Mercaderías",
        c: "Alquiler del local",
        d: "Herramientas consumibles",
        correct: "c",
    },
    {
        question: "¿Qué son los costes variables?",
        a: "Costes que varían con el volumen de producción de la empresa",
        b: "Costes que no varían con el volumen de producción",
        c: "Costes imposibles de predecir",
        d: "Costes que solo afectan a la calidad del producto",
        correct: "a",
    },
    {
        question: "¿Cuál de los siguientes es un ejemplo de coste variable?",
        a: "Seguros",
        b: "Impuesto de Bienes Inmuebles (IBI)",
        c: "Salarios de trabajadores fijos",
        d: "Materias primas",
        correct: "d",
    },
    {
        question: "¿Cómo se calcula el Coste Total (CT)?",
        a: "CT = Costes Variables - Costes Fijos",
        b: "CT = Costes Fijos + Costes Variables",
        c: "CT = Costes Fijos × Costes Variables",
        d: "CT = Costes Variables ÷ Costes Fijos",
        correct: "b",
    },
    {
        question: "¿Cómo se calcula el Coste Variable Medio (CVMe)?",
        a: "CVMe = Costes Variables ÷ Cantidad de unidades",
        b: "CVMe = Costes Variables × Cantidad de unidades",
        c: "CVMe = Costes Variables + Cantidad de unidades",
        d: "CVMe = Costes Fijos ÷ Costes Variables",
        correct: "a",
    },
    {
        question: "¿Cómo se calcula el Coste Total Medio (CTMe)?",
        a: "CTMe = Coste Total × Cantidad de unidades",
        b: "CTMe = Coste Total ÷ Cantidad de unidades",
        c: "CTMe = Coste Total + Cantidad de unidades",
        d: "CTMe = Coste Total - Cantidad de unidades",
        correct: "b",
    },
    {
        question: "¿Qué indica el Coste Total Medio?",
        a: "Lo que cuesta producir en total",
        b: "Lo que cuesta cada unidad en total",
        c: "Lo que cuesta vender el producto",
        d: "Lo que cuesta la materia prima",
        correct: "b",
    },
    {
        question: "¿Qué relación debe existir entre el precio de venta y el Coste Total Medio si queremos obtener beneficios?",
        a: "El precio de venta debe ser igual al Coste Total Medio",
        b: "El precio de venta debe ser inferior al Coste Total Medio",
        c: "El precio de venta debe ser superior al Coste Total Medio",
        d: "No existe relación entre ambos",
        correct: "c",
    },
    {
        question: "¿Qué fórmula determina a partir de qué cantidad es preferible producir a comprar?",
        a: "Q = Coste Fijo ÷ (Precio de compra - CVMe)",
        b: "Q = Coste Variable ÷ (Precio de compra - Coste Fijo)",
        c: "Q = Precio de compra ÷ (Coste Fijo - CVMe)",
        d: "Q = CVMe ÷ (Precio de compra - Coste Fijo)",
        correct: "a",
    },
    {
        question: "¿Qué es el precio técnico?",
        a: "El precio que establece el fabricante",
        b: "El precio con el que cubrimos todos los costes",
        c: "El precio recomendado por el sector",
        d: "El precio máximo que está dispuesto a pagar el cliente",
        correct: "b",
    },
    {
        question: "¿Cómo se calcula el precio de venta a partir del precio técnico?",
        a: "PV = Precio técnico - Margen",
        b: "PV = Precio técnico × (1 + Margen)",
        c: "PV = Precio técnico ÷ Margen",
        d: "PV = Precio técnico + Coste Total",
        correct: "b",
    },
    {
        question: "Si el precio técnico de un producto es de 29,42€ y queremos obtener un margen del 50%, ¿cuál será el precio de venta?",
        a: "44,13€",
        b: "14,71€",
        c: "79,42€",
        d: "58,84€",
        correct: "a",
    },
    {
        question: "¿Cómo se calcula el beneficio en una empresa?",
        a: "B = Ingresos Totales + Costes Totales",
        b: "B = Ingresos Totales - Costes Totales",
        c: "B = Ingresos Totales × Costes Totales",
        d: "B = Costes Totales - Ingresos Totales",
        correct: "b",
    },
    {
        question: "¿Qué es el umbral de rentabilidad o punto muerto?",
        a: "La cifra de ventas en la que los ingresos y los costes fijos son iguales",
        b: "La cifra de ventas en la que los ingresos y los costes totales son iguales",
        c: "La cifra de ventas que maximiza los beneficios",
        d: "La cifra de ventas que minimiza los costes",
        correct: "b",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}