/**
 * Datos del quiz de Empresa e Iniciativa Emprendedora - Recursos Humanos
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "¿Qué elementos se analizan en el Plan de Recursos Humanos?",
        a: "Únicamente la definición de capacidades",
        b: "Solo la selección y contratación del personal",
        c: "Política de personal, organización funcional, estructura de plantilla, selección, etc.",
        d: "Exclusivamente la dimensión y estructura de la plantilla",
        correct: "c",
    },
    {
        question: "¿Qué trata de estructurar la organización funcional?",
        a: "Solo los espacios físicos de la empresa",
        b: "Los recursos humanos e integrarlos con los recursos materiales",
        c: "Únicamente los horarios laborales",
        d: "Solo los salarios de los empleados",
        correct: "b",
    },
    {
        question: "¿Cuál de los siguientes NO es un objetivo de la organización funcional?",
        a: "Determinar la organización de la empresa: áreas, relaciones, jerarquía",
        b: "Organizar las tareas de cada empleado cuantitativa y cualitativamente",
        c: "Establecer la importancia de cada tarea en términos absolutos y comparativos",
        d: "Minimizar el número de empleados independientemente de las necesidades",
        correct: "d",
    },
    {
        question: "¿Qué define el plan de contratación?",
        a: "Solo el tipo de contrato que vinculará a los empleados",
        b: "Tipo de contrato, condiciones laborales y coste de los empleados",
        c: "Únicamente el coste de los empleados",
        d: "Solo la duración de los contratos",
        correct: "b",
    },
    {
        question: "Según el Plan de Contratación, ¿es necesario que todos los empleados tengan contrato a jornada completa?",
        a: "Sí, siempre es obligatorio",
        b: "No, en algunos casos puede ser suficiente contratar a tiempo parcial o por temporada",
        c: "Sí, es un requisito legal en todas las empresas",
        d: "Depende del sector, pero generalmente sí",
        correct: "b",
    },
    {
        question: "¿Qué factores debe considerar un empresario al establecer la política salarial?",
        a: "Solo el mercado de trabajo",
        b: "Exclusivamente los convenios colectivos",
        c: "Mercado laboral, cualificación, experiencia, convenios colectivos, costes, etc.",
        d: "Únicamente la experiencia del trabajador",
        correct: "c",
    },
    {
        question: "¿Qué es la externalización de funciones?",
        a: "Contratar empleados en el extranjero",
        b: "Desarrollar funciones especializadas a través de consultores externos",
        c: "Tercerizar toda la empresa",
        d: "Exportar productos a otros países",
        correct: "b",
    },
    {
        question: "¿Qué funciones suelen externalizarse con más frecuencia?",
        a: "Las funciones principales de la empresa",
        b: "Funciones de producción",
        c: "Funciones especializadas como temas jurídicos, tecnológicos o comerciales",
        d: "Funciones de atención al cliente",
        correct: "c",
    },
    {
        question: "¿Qué es un profesiograma?",
        a: "Un calendario laboral",
        b: "Un análisis detallado de un puesto de trabajo",
        c: "Un tipo de contrato laboral",
        d: "Un documento para el registro de horarios",
        correct: "b",
    },
    {
        question: "¿Cuál de los siguientes es un estilo de dirección según el material estudiado?",
        a: "Estilo visionario",
        b: "Estilo participativo",
        c: "Estilo transformacional",
        d: "Estilo sistemático",
        correct: "b",
    },
    {
        question: "En el estilo de dirección participativo...",
        a: "El jefe impone las normas y sus criterios",
        b: "Se comparte la responsabilidad con los subordinados en la toma de decisiones",
        c: "El grupo toma decisiones libremente sin la participación del jefe",
        d: "Se da prioridad a los intereses personales sobre las necesidades organizacionales",
        correct: "b",
    },
    {
        question: "¿Qué caracteriza al estilo de dirección autocrático?",
        a: "El jefe comparte responsabilidades con los empleados",
        b: "Las tareas se discuten y determinan en grupo",
        c: "El jefe impone las normas y criterios, mantiene un comportamiento enérgico y firme",
        d: "El grupo toma decisiones libremente sin participación del jefe",
        correct: "c",
    },
    {
        question: "En el estilo de dirección democrático...",
        a: "El jefe impone las normas y sus criterios",
        b: "Las tareas se discuten y determinan en grupo, el jefe orienta y apoya",
        c: "El grupo toma decisiones sin participación del jefe",
        d: "Se da prioridad a los intereses personales frente a las necesidades de la organización",
        correct: "b",
    },
    {
        question: "¿Qué caracteriza al estilo de dirección laissez-faire?",
        a: "El jefe impone todas las normas",
        b: "Las tareas se discuten en grupo con la orientación del jefe",
        c: "El grupo toma decisiones libremente sin la participación del jefe",
        d: "Se establece una actitud protectora con los subordinados",
        correct: "c",
    },
    {
        question: "¿Qué caracteriza al estilo de dirección paternalista?",
        a: "Da prioridad a los intereses personales y establece una actitud protectora",
        b: "El jefe comparte responsabilidades con los empleados",
        c: "El grupo toma decisiones sin la participación del jefe",
        d: "Establecimiento de una estructura jerárquica rígida con normas estrictas",
        correct: "a",
    },
    {
        question: "En el estilo de dirección burocrático...",
        a: "El jefe comparte responsabilidades con los empleados",
        b: "Se establece una estructura jerárquica con normas, bloqueándose la comunicación",
        c: "Las tareas se discuten y determinan en grupo",
        d: "El jefe establece una actitud protectora con los subordinados",
        correct: "b",
    },
    {
        question: "¿Qué teoría de liderazgo distingue entre la teoría X y la teoría Y?",
        a: "Teoría de Blake y Mouton",
        b: "Teoría de Hersey y Blanchard",
        c: "Teoría de Douglas McGregor",
        d: "Teoría de Maslow",
        correct: "c",
    },
    {
        question: "¿Qué teoría de liderazgo propone la malla gerencial?",
        a: "Teoría de Douglas McGregor",
        b: "Teoría de Blake y Mouton",
        c: "Teoría de Hersey y Blanchard",
        d: "Teoría de Vroom",
        correct: "b",
    },
    {
        question: "¿Qué teoría de motivación postula una jerarquía de necesidades humanas?",
        a: "Teoría de Herzberg",
        b: "Teoría de McClelland",
        c: "Teoría de Maslow",
        d: "Teoría de Vroom",
        correct: "c",
    },
    {
        question: "La teoría bifactorial de motivación fue propuesta por:",
        a: "Maslow",
        b: "Herzberg",
        c: "McClelland",
        d: "Vroom",
        correct: "b",
    },
    {
        question: "¿Cuál de las siguientes es una técnica de motivación laboral?",
        a: "Reducir los salarios progresivamente",
        b: "Evitar la participación de los empleados en decisiones",
        c: "Enriquecimiento del trabajo",
        d: "Mantener tareas monótonas y repetitivas",
        correct: "c",
    },
    {
        question: "¿En qué consiste la técnica de motivación 'reconocimiento del trabajo efectuado'?",
        a: "Evitar elogiar a los empleados",
        b: "Reconocer y elogiar el trabajo bien hecho, inmediatamente después del comportamiento",
        c: "Criticar públicamente los errores",
        d: "Ignorar los logros para mantener la competitividad",
        correct: "b",
    },
    {
        question: "¿Qué es la escucha activa como técnica de motivación?",
        a: "Ignorar deliberadamente los problemas del personal",
        b: "Escuchar música durante las horas de trabajo",
        c: "Interés y comprensión del superior al subordinado, mejorando relaciones",
        d: "Sistema de audio para controlar las conversaciones",
        correct: "c",
    },
    {
        question: "¿Qué técnica de motivación permite que el empleado mejore sus competencias y pueda promocionar?",
        a: "Participación y delegación",
        b: "Formación y desarrollo profesional",
        c: "Círculos de calidad",
        d: "Establecimiento de objetivos",
        correct: "b",
    },
    {
        question: "¿Qué son los círculos de calidad?",
        a: "Reuniones exclusivas de la dirección",
        b: "Pequeño grupo de trabajadores del mismo área que se reúnen para mejorar calidad y productividad",
        c: "Certificaciones de calidad ISO",
        d: "Sistemas de control automático de calidad",
        correct: "b",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}