/**
 * Datos del quiz de Empresa e Iniciativa Emprendedora - Financiación Empresarial
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "¿Cuál es la diferencia principal entre un gasto y una inversión?",
        a: "Un gasto siempre es mayor que una inversión",
        b: "Una inversión se recupera a corto plazo, un gasto a largo plazo",
        c: "Una inversión es un bien imprescindible para obtener el producto que no se vende, un gasto es lo que se consume",
        d: "No hay diferencia, son términos intercambiables",
        correct: "c",
    },
    {
        question: "¿Cuál de los siguientes es un ejemplo de inversión?",
        a: "Materias primas",
        b: "Salarios",
        c: "Publicidad",
        d: "Maquinaria",
        correct: "d",
    },
    {
        question: "¿Cuál de los siguientes es un ejemplo de gasto?",
        a: "Vehículos",
        b: "Alquileres",
        c: "Equipos informáticos",
        d: "Mobiliario",
        correct: "b",
    },
    {
        question: "¿Qué son las fuentes de financiación propias?",
        a: "Dinero aportado por los bancos",
        b: "Recursos financieros que pertenecen a la empresa o sus socios",
        c: "Subvenciones del Estado",
        d: "Préstamos a largo plazo",
        correct: "b",
    },
    {
        question: "¿Qué son las fuentes de financiación ajenas?",
        a: "Recursos financieros que pertenecen a la empresa o sus socios",
        b: "Fondos procedentes de terceros que hay que devolver",
        c: "Beneficios no distribuidos de ejercicios anteriores",
        d: "Aportaciones de los socios",
        correct: "b",
    },
    {
        question: "¿Qué tipo de financiación es el Capital Social?",
        a: "Financiación ajena externa",
        b: "Financiación ajena interna",
        c: "Financiación propia externa",
        d: "Financiación propia interna",
        correct: "c",
    },
    {
        question: "¿Qué tipo de financiación son las Reservas?",
        a: "Financiación ajena externa",
        b: "Financiación ajena interna",
        c: "Financiación propia externa",
        d: "Financiación propia interna",
        correct: "d",
    },
    {
        question: "¿Qué son los Business Angels?",
        a: "Empresas que ofrecen subvenciones a fondo perdido",
        b: "Inversores individuales que invierten en empresas con alto potencial de crecimiento",
        c: "Entidades financieras especializadas en préstamos para emprendedores",
        d: "Aceleradoras de empresas públicas",
        correct: "b",
    },
    {
        question: "¿Qué son las Sociedades de Capital Riesgo?",
        a: "Entidades que invierten en empresas con problemas financieros",
        b: "Empresas que invierten en negocios para vender su participación a medio plazo",
        c: "Gestoras de subvenciones públicas para emprendedores",
        d: "Fondos de inversión exclusivos para grandes corporaciones",
        correct: "b",
    },
    {
        question: "¿Qué significa FFF en el contexto de la financiación?",
        a: "Fast, Focus, Forward",
        b: "Fair, Fast, Flexible",
        c: "Family, Friends, Fools",
        d: "Financial, Fiscal, Flexible",
        correct: "c",
    },
    {
        question: "¿Cuál es la principal diferencia entre un préstamo y un crédito?",
        a: "En el préstamo se recibe todo el dinero al inicio, en el crédito se dispone según necesidades",
        b: "El préstamo es a corto plazo, el crédito a largo plazo",
        c: "El préstamo cobra más intereses que el crédito",
        d: "El crédito requiere siempre garantías hipotecarias",
        correct: "a",
    },
    {
        question: "¿Qué es el renting?",
        a: "Compra de un bien con opción de alquiler futuro",
        b: "Alquiler de un bien con opción a compra en el futuro",
        c: "Alquiler de un bien incluyendo seguros, revisiones y mantenimientos",
        d: "Compra financiada de un bien a largo plazo",
        correct: "c",
    },
    {
        question: "¿Qué es el leasing?",
        a: "Alquiler de un bien incluyendo seguros y mantenimientos",
        b: "Alquiler de un bien con opción a compra en el futuro",
        c: "Compra de un bien con financiación bancaria",
        d: "Préstamo a largo plazo con garantía hipotecaria",
        correct: "b",
    },
    {
        question: "¿Para qué tipo de bienes es más recomendable el renting?",
        a: "Bienes inmuebles como locales comerciales",
        b: "Bienes que pueden quedarse obsoletos como vehículos u ordenadores",
        c: "Bienes de gran valor y larga duración",
        d: "Bienes de segunda mano",
        correct: "b",
    },
    {
        question: "¿Para qué tipo de bienes es más recomendable el leasing?",
        a: "Bienes de bajo valor como mobiliario de oficina",
        b: "Bienes de corta vida útil como equipos informáticos",
        c: "Equipos caros con una vida larga como maquinaria o locales",
        d: "Bienes de consumo rápido",
        correct: "c",
    },
    {
        question: "¿Qué tipo de financiación ofrecen los proveedores?",
        a: "Subvenciones a fondo perdido",
        b: "Posibilidad de pagar mercaderías o materias primas a 30 o 60 días",
        c: "Préstamos a largo plazo",
        d: "Inversión a cambio de participación en la empresa",
        correct: "b",
    },
    {
        question: "¿Qué es el descuento de letras y pagarés?",
        a: "Reducción en el precio de compra por pago al contado",
        b: "Banco paga por adelantado letras o pagarés a cambio de comisión e intereses",
        c: "Método de valoración de activos financieros",
        d: "Sistema de reducción de impuestos para empresas",
        correct: "b",
    },
    {
        question: "¿En qué consiste el confirming?",
        a: "Pagar a los proveedores puntualmente aunque no tengas dinero en cuenta",
        b: "Confirmar la recepción de mercancías",
        c: "Sistema de clasificación de proveedores según su fiabilidad",
        d: "Método de validación de facturas",
        correct: "a",
    },
    {
        question: "¿Qué es el factoring?",
        a: "Sistema para calcular el coste real de los productos",
        b: "Una empresa se responsabiliza del pago de facturas de clientes a cambio de comisión",
        c: "Método para reducir los costes de producción",
        d: "Sistema para gestionar el inventario de la empresa",
        correct: "b",
    },
    {
        question: "¿Qué es el crowdfunding?",
        a: "Sistema para contratar empleados en masa",
        b: "Sistema de cooperación que permite reunir dinero entre muchas personas para apoyar un proyecto",
        c: "Método de marketing digital",
        d: "Sistema de franquicias colectivas",
        correct: "b",
    },
    {
        question: "¿Qué es una aceleradora de empresas?",
        a: "Un espacio físico que alquila oficinas a nuevas empresas",
        b: "Una empresa que ayuda a crear páginas web muy rápidas",
        c: "Un programa que ayuda a poner en marcha startups con formación, mentores y posible financiación",
        d: "Una consultoría especializada en marketing online",
        correct: "c",
    },
    {
        question: "¿Qué es un vivero de empresas?",
        a: "Una empresa dedicada a la jardinería corporativa",
        b: "Un espacio físico diseñado para acoger empresas de nueva creación",
        c: "Un sistema de subvenciones para agricultura",
        d: "Un departamento dentro de grandes corporaciones",
        correct: "b",
    },
    {
        question: "¿Qué tipo de ayuda ofrece la línea ICO-Emprendedores?",
        a: "Subvenciones a fondo perdido",
        b: "Préstamos en condiciones muy ventajosas",
        c: "Capital riesgo para startups",
        d: "Exenciones fiscales",
        correct: "b",
    },
    {
        question: "¿Qué es el capital semilla o seed capital?",
        a: "Financiación para empresas agrícolas",
        b: "Inversión temprana en ideas de negocio o empresas recién creadas",
        c: "Fondo de inversión para comprar acciones en bolsa",
        d: "Ayudas para comprar la primera sede de la empresa",
        correct: "b",
    },
    {
        question: "¿Qué tipo de financiación es el capital de expansión o growth capital?",
        a: "Financiación para la internacionalización o nuevas inversiones de una empresa con beneficios",
        b: "Inversión en empresas en crisis que necesitan reestructuración",
        c: "Financiación para la compra de empresas ya existentes",
        d: "Inversión temprana en startups sin ventas",
        correct: "a",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}