/**
 * Datos del quiz de Empresa e Iniciativa Emprendedora - 4º Trimestre: El Entorno de la Empresa
 * Basado en la Unidad 2 del temario
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "¿Qué es el entorno según el material estudiado?",
        a: "Únicamente los competidores directos de la empresa",
        b: "Factores externos a la empresa que tienen influencia significativa en su estrategia empresarial",
        c: "Solamente los factores internos de la empresa",
        d: "Exclusivamente el marco legal en el que opera la empresa",
        correct: "b",
    },
    {
        question: "Según la Teoría General de Sistemas (TGS), un sistema se define como:",
        a: "Un conjunto de elementos aislados",
        b: "Un conjunto de procesos lineales",
        c: "Un conjunto de elementos interrelacionados, diseñado para alcanzar un objetivo específico",
        d: "Un conjunto de reglas para administrar una empresa",
        correct: "c",
    },
    {
        question: "La empresa como sistema se entiende como:",
        a: "Un ente aislado sin relación con el exterior",
        b: "Un conjunto de elementos relacionados entre sí y con el sistema económico global",
        c: "Un organismo independiente del entorno",
        d: "Una estructura estática que no interactúa con el mercado",
        correct: "b",
    },
    {
        question: "¿Cuál de estas características NO define el entorno actual de las empresas?",
        a: "Cambios muy rápidos",
        b: "Globalización",
        c: "Estabilidad y previsibilidad",
        d: "Importancia de las TIC",
        correct: "c",
    },
    {
        question: "¿En qué niveles se distingue el entorno según el material estudiado?",
        a: "Entorno favorable y entorno hostil",
        b: "Entorno estable y entorno dinámico",
        c: "Entorno simple y entorno complejo",
        d: "Entorno general (macroentorno) y entorno específico (microentorno)",
        correct: "d",
    },
    {
        question: "El entorno general o macroentorno de la empresa se refiere a:",
        a: "Factores internos controlables por la empresa",
        b: "Factores que afectan solo a una empresa concreta",
        c: "Factores externos que pueden influir en los resultados de todas las empresas",
        d: "El conjunto de los competidores directos",
        correct: "c",
    },
    {
        question: "¿Cuál de los siguientes NO es un factor del entorno general o macroentorno?",
        a: "Factores económicos",
        b: "Factores socioculturales",
        c: "Factores competitivos directos",
        d: "Factores tecnológicos",
        correct: "c",
    },
    {
        question: "El microentorno o entorno específico está formado por:",
        a: "Factores que afectan a todas las empresas de un país",
        b: "Variables que afectan solamente a las empresas de un sector",
        c: "El organigrama interno de la empresa",
        d: "Exclusivamente los clientes de la empresa",
        correct: "b",
    },
    {
        question: "¿Cuál de los siguientes NO es un elemento del entorno específico o microentorno?",
        a: "La competencia",
        b: "Los productos sustitutivos",
        c: "Los factores político-legales",
        d: "Los proveedores",
        correct: "c",
    },
    {
        question: "La amenaza de entrada de nuevos competidores en un sector se denomina:",
        a: "Competencia potencial",
        b: "Competencia desleal",
        c: "Diversificación",
        d: "Concentración del mercado",
        correct: "a",
    },
    {
        question: "¿Qué representan los productos sustitutivos en el microentorno de una empresa?",
        a: "Productos idénticos a los de la empresa",
        b: "Productos que cubren las mismas necesidades que los de la empresa",
        c: "Productos complementarios a los de la empresa",
        d: "Productos fabricados por la misma empresa",
        correct: "b",
    },
    {
        question: "Un entorno empresarial con pocos cambios y alta previsibilidad se denomina:",
        a: "Entorno dinámico",
        b: "Entorno complejo",
        c: "Entorno estable",
        d: "Entorno hostil",
        correct: "c",
    },
    {
        question: "Un entorno con numerosos factores interrelacionados y difíciles de comprender se considera:",
        a: "Entorno dinámico",
        b: "Entorno complejo",
        c: "Entorno estable",
        d: "Entorno favorable",
        correct: "b",
    },
    {
        question: "Un ejemplo de entorno hostil sería:",
        a: "Una tienda de alimentos básicos durante una crisis económica",
        b: "Una discoteca en una zona de pubs",
        c: "Una inmobiliaria durante la crisis inmobiliaria",
        d: "Un taller mecánico en un barrio residencial",
        correct: "c",
    },
    {
        question: "La matriz DAFO permite a la empresa:",
        a: "Únicamente analizar sus fortalezas internas",
        b: "Detectar oportunidades y amenazas del entorno e identificar cambios internos necesarios",
        c: "Solo evaluar a la competencia",
        d: "Calcular sus beneficios potenciales",
        correct: "b",
    },
    {
        question: "¿Qué significan las siglas DAFO?",
        a: "Desarrollo, Análisis, Formación y Organización",
        b: "Debilidades, Amenazas, Fortalezas y Oportunidades",
        c: "Dirección, Administración, Finanzas y Operaciones",
        d: "Diagnóstico, Acciones, Funciones y Objetivos",
        correct: "b",
    },
    {
        question: "Las debilidades en un análisis DAFO son:",
        a: "Factores positivos externos a la empresa",
        b: "Factores negativos externos a la empresa",
        c: "Elementos internos que perjudican a la empresa",
        d: "Elementos positivos internos de la empresa",
        correct: "c",
    },
    {
        question: "Las fortalezas en un análisis DAFO son:",
        a: "Factores positivos externos a la empresa",
        b: "Factores negativos externos a la empresa",
        c: "Elementos internos que perjudican a la empresa",
        d: "Puntos fuertes internos de la empresa",
        correct: "d",
    },
    {
        question: "Las amenazas en un análisis DAFO representan:",
        a: "Factores positivos externos a la empresa",
        b: "Dificultades que provienen del exterior perjudicando a la empresa",
        c: "Elementos internos que perjudican a la empresa",
        d: "Elementos positivos internos de la empresa",
        correct: "b",
    },
    {
        question: "Las oportunidades en un análisis DAFO son:",
        a: "Elementos positivos que provienen del exterior",
        b: "Factores negativos externos a la empresa",
        c: "Elementos internos que perjudican a la empresa",
        d: "Puntos fuertes internos de la empresa",
        correct: "a",
    },
    {
        question: "La estrategia que combina fortalezas con oportunidades se denomina:",
        a: "Estrategia defensiva",
        b: "Estrategia de supervivencia",
        c: "Estrategia de reorientación",
        d: "Estrategia ofensiva",
        correct: "d",
    },
    {
        question: "La estrategia que combina debilidades con amenazas se denomina:",
        a: "Estrategia defensiva",
        b: "Estrategia de supervivencia",
        c: "Estrategia de reorientación",
        d: "Estrategia ofensiva",
        correct: "b",
    },
    {
        question: "¿Qué es la Responsabilidad Social de la Empresa según el material?",
        a: "La obligación legal de pagar impuestos",
        b: "El conjunto de obligaciones y compromisos legales y éticos ante los grupos de interés",
        c: "La obligación de generar beneficios para los accionistas",
        d: "La organización interna de la empresa",
        correct: "b",
    },
    {
        question: "El compromiso de las empresas que les hace preocuparse no solo por sus intereses económicos sino también por la repercusión de sus actividades en la sociedad se denomina:",
        a: "Ética empresarial",
        b: "Responsabilidad Social de la Empresa",
        c: "Balance económico",
        d: "Planificación estratégica",
        correct: "b",
    },
    {
        question: "¿Cuál de estos NO es un ámbito de la Responsabilidad Social Empresarial según el material?",
        a: "Económico",
        b: "Recursos humanos",
        c: "Medioambiental",
        d: "Político-partidista",
        correct: "d",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}