/**
 * Datos del quiz de Empresa e Iniciativa Emprendedora - 3º Trimestre: Iniciativa Emprendedora
 * Basado en la Unidad 1 del temario
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "¿Qué es un emprendedor según el material visto?",
        a: "Persona que hereda una empresa familiar",
        b: "Persona capaz de convertir en realidad una idea concreta",
        c: "Persona que solo busca beneficios económicos",
        d: "Persona que únicamente crea empresas de gran tamaño",
        correct: "b",
    },
    {
        question: "¿Qué es el espíritu emprendedor?",
        a: "La obligación de crear empresas para generar empleo",
        b: "La habilidad para gestionar equipos de trabajo",
        c: "La capacidad innovadora para probar cosas nuevas o hacerlas de manera diferente",
        d: "La aptitud para calcular beneficios empresariales",
        correct: "c",
    },
    {
        question: "¿Cuál de las siguientes NO es una característica propia de los emprendedores?",
        a: "Creatividad",
        b: "Autonomía",
        c: "Dependencia de supervisión constante",
        d: "Capacidad para asumir riesgos",
        correct: "c",
    },
    {
        question: "La capacidad para imaginar ideas y proyectos nuevos y proponer soluciones originales corresponde a la característica de:",
        a: "Liderazgo",
        b: "Tenacidad",
        c: "Creatividad",
        d: "Sentido de responsabilidad",
        correct: "c",
    },
    {
        question: "¿Qué implica la característica de 'Autonomía' en un emprendedor?",
        a: "No necesitar supervisión inmediata",
        b: "No trabajar en equipo bajo ninguna circunstancia",
        c: "No aceptar consejos de otros profesionales",
        d: "No tener jefes ni socios en la empresa",
        correct: "a",
    },
    {
        question: "¿Qué significa tener 'Sentido de la responsabilidad' como emprendedor?",
        a: "Asumir únicamente los éxitos del proyecto",
        b: "Tendencia a cumplir las obligaciones contraídas con otros y consigo mismo",
        c: "Delegar todas las tareas importantes en otras personas",
        d: "No asumir riesgos para evitar fracasos",
        correct: "b",
    },
    {
        question: "¿Qué tipo de emprendedor es aquel que desarrolla proyectos innovadores siendo trabajador por cuenta ajena?",
        a: "Empresario",
        b: "Emprendedor social",
        c: "Intraemprendedor o emprendedor corporativo",
        d: "Emprendedor autónomo",
        correct: "c",
    },
    {
        question: "Según el material, ¿qué empresas son ejemplos de tener implantada una cultura emprendedora?",
        a: "Pequeñas empresas tradicionales",
        b: "Empresas familiares de segunda generación",
        c: "Google, Apple, 3M (Post-it)",
        d: "Únicamente startups tecnológicas",
        correct: "c",
    },
    {
        question: "¿Cuál de estas NO es una ventaja de ser empresario según el material?",
        a: "Ser tu propio jefe",
        b: "Obtener beneficios garantizados",
        c: "Libertad (horarios, decisiones...)",
        d: "Prestigio social",
        correct: "b",
    },
    {
        question: "¿Cuál de estas es una desventaja de ser empresario según el material?",
        a: "Reconocimiento profesional",
        b: "Libertad para tomar decisiones",
        c: "Aprendizaje continuo",
        d: "Asumir riesgos",
        correct: "d",
    },
    {
        question: "¿Qué concepto se define como la generación de nuevas ideas?",
        a: "Innovación",
        b: "Creatividad",
        c: "Espíritu emprendedor",
        d: "Liderazgo",
        correct: "b",
    },
    {
        question: "¿Qué concepto se define como la implantación de nuevas ideas?",
        a: "Innovación",
        b: "Creatividad",
        c: "Espíritu emprendedor",
        d: "Liderazgo",
        correct: "a",
    },
    {
        question: "¿Cuál es el punto de partida de todo proyecto empresarial según el material?",
        a: "La financiación",
        b: "El plan de marketing",
        c: "La idea",
        d: "El equipo directivo",
        correct: "c",
    },
    {
        question: "¿Cuál de estas formas de búsqueda de ideas de negocio NO aparece en el material?",
        a: "Aprovechar la propia experiencia como trabajador",
        b: "Innovación en productos, servicios o procesos",
        c: "Copiar literalmente ideas de la competencia",
        d: "Percibir una necesidad no satisfecha en el mercado",
        correct: "c",
    },
    {
        question: "La innovación que consiste en crear un producto que no existe en el mercado se denomina:",
        a: "Innovación parcial",
        b: "Innovación total",
        c: "Innovación disruptiva",
        d: "Innovación incremental",
        correct: "b",
    },
    {
        question: "Cuando se mejora un producto ya existente, como cuando se creó la TV en color, es un ejemplo de:",
        a: "Innovación total",
        b: "Innovación que no aporta nada nuevo",
        c: "Innovación que aporta algo nuevo al producto",
        d: "Ninguna de las anteriores",
        correct: "c",
    },
    {
        question: "¿Qué tipo de innovación fue la que aplicó McDonald's al utilizar el concepto de línea de producción?",
        a: "Innovación de producto",
        b: "Innovación de proceso",
        c: "Innovación tecnológica",
        d: "Innovación en marketing",
        correct: "b",
    },
    {
        question: "La aplicación del conocimiento científico a la actividad de la empresa se denomina:",
        a: "Innovación de proceso",
        b: "Innovación de producto",
        c: "Innovación tecnológica",
        d: "Innovación en organización",
        correct: "c",
    },
    {
        question: "¿Qué tipo de innovación consistiría en cambiar el envase del producto, como hizo Solán de Cabras con su botella azul?",
        a: "Innovación de producto",
        b: "Innovación de proceso",
        c: "Innovación tecnológica",
        d: "Innovación en marketing",
        correct: "d",
    },
    {
        question: "¿Qué tipo de innovación permite que las empresas den servicio a sus clientes a través de plataformas de pago y servicios de gestión online?",
        a: "Innovación tecnológica",
        b: "Innovación en la organización de la empresa",
        c: "Innovación de proceso",
        d: "Innovación de producto",
        correct: "b",
    },
    {
        question: "Según el material, la idea al ser valorada inicialmente debe:",
        a: "Ser totalmente original sin competencia en el mercado",
        b: "Tener un factor diferenciador o satisfacer alguna necesidad",
        c: "Ser fácil de implementar sin grandes inversiones",
        d: "Generar beneficios desde el primer momento",
        correct: "b",
    },
    {
        question: "¿Cuál de estas preguntas NO debemos hacernos al valorar nuestra idea de negocio según el material?",
        a: "¿Por qué vas a vender?",
        b: "¿Qué ofreces a los clientes para que compren?",
        c: "¿Cuánto beneficio obtendrás en el primer año?",
        d: "¿Qué tiene el producto para que sea distinto de la competencia?",
        correct: "c",
    },
    {
        question: "¿Qué características define el material sobre la figura del emprendedor?",
        a: "VE, PIENSA y HACE lo mismo que los demás para minimizar riesgos",
        b: "VE lo que todos han visto, PIENSA lo que nadie más ha pensado, HACE lo que nadie más ha hecho",
        c: "VE oportunidades, PIENSA en rendimiento económico, HACE dinero rápidamente",
        d: "VE, PIENSA y HACE exactamente lo mismo que sus competidores",
        correct: "b",
    },
    {
        question: "Según el material, la cultura emprendedora se define como:",
        a: "La capacidad para crear empresas exclusivamente tecnológicas",
        b: "El conjunto de cualidades, habilidades y conocimientos necesarios para gestionar el propio proyecto o crear su propio negocio",
        c: "La forma de dirigir una empresa ya establecida",
        d: "La capacidad para encontrar financiación pública para proyectos empresariales",
        correct: "b",
    },
    {
        question: "¿Qué es el autoempleo según el material estudiado?",
        a: "Trabajar solo, sin empleados",
        b: "Actividad profesional o empresarial generada por una persona que la ejerce de forma directa",
        c: "Crear empresas para otros emprendedores",
        d: "Trabajar exclusivamente desde casa",
        correct: "b",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}