/**
 * Datos del quiz de Inglés Técnico - Repaso General 2
 * Archivo de repaso con preguntas de todos los temas
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "Choose the best definition for 'peripheral'",
        a: "A part or element of a larger whole, especially a part of a machine or vehicle.",
        b: "A peripheral is an input or output device that gives a computer additional functionality",
        c: "The programs and other operating information used by a computer.",
        d: "None of the answers are correct",
        correct: "b",
    },
    {
        question: "Which of the following can be considered peripherals?",
        a: "External drive, hard disk drive and optical drive",
        b: "Printer, keyboard and SSD",
        c: "External drive, hard disk drive and optical drive",
        d: "Mouse, monitor and keyboard",
        correct: "d",
    },
    {
        question: "What is an application developer?",
        a: "He/ She is an IT professional who develops (designs and writes) the software code for applications",
        b: "He/she is an IT professional in charge of implementing and maintaining a company's network of computer",
        c: "He/she is an IT professional in charge of planning a company's network of computer",
        d: "He/ She is someone who manages any kind of technological system",
        correct: "a",
    },
    {
        question: "Which of these is not a type of network?",
        a: "Mesh",
        b: "Ring",
        c: "Star",
        d: "Browser",
        correct: "d",
    },
    {
        question: "If you don't install a firework your network will be very...",
        a: "seamless",
        b: "clunky",
        c: "vulnerable",
        d: "sophisticated",
        correct: "c",
    },
    {
        question: "Which one is NOT a type of malware?",
        a: "Trojan",
        b: "Worm",
        c: "Spyware",
        d: "VPN",
        correct: "d",
    },
    {
        question: "API refers to...",
        a: "Application Programming Interface",
        b: "Application Programming Individual",
        c: "Advanced Programming Interface",
        d: "Advanced Perfect Interface.",
        correct: "a",
    },
    {
        question: "Which IT professional earns the highest salary according to the infographics?",
        a: "Web Developer",
        b: "Computer Engineer",
        c: "Computer Scientist",
        d: "Hardware Engineer",
        correct: "c",
    },
    {
        question: "What does a motherboard consist of?",
        a: "A large circuit board with integrated chipsets and controllers",
        b: "A series of storage devices connected together",
        c: "Multiple CPUs working together",
        d: "Software that controls hardware components",
        correct: "a",
    },
    {
        question: "What is the function of a CPU?",
        a: "To store information permanently",
        b: "To process instructions and control the rest of the hardware",
        c: "To display graphical user interface",
        d: "To connect peripherals to the computer",
        correct: "b",
    },
    {
        question: "What is another term for 'programmers'?",
        a: "Software mechanics",
        b: "Code architects",
        c: "Software developers",
        d: "Computer scientists",
        correct: "c",
    },
    {
        question: "What is an example of open source software mentioned in the text?",
        a: "Microsoft Windows",
        b: "Adobe Photoshop",
        c: "Mozilla Firefox",
        d: "Microsoft Office",
        correct: "c",
    },
    {
        question: "What is a shared server?",
        a: "A computer used for hosting multiple websites",
        b: "A peer-to-peer network",
        c: "A server that divides files equally between users",
        d: "A computer exclusively used by one company",
        correct: "a",
    },
    {
        question: "What does 'uptime' refer to in web hosting?",
        a: "The time it takes to upload files",
        b: "The time during which a server is in operation",
        c: "The time it takes to update software",
        d: "The time it takes to install an operating system",
        correct: "b",
    },
    {
        question: "What is the difference between LANs and WANs?",
        a: "LANs use wireless connections, WANs use cables",
        b: "LANs are faster than WANs",
        c: "LANs connect computers in the same building, WANs cover larger areas",
        d: "LANs are for businesses, WANs are for homes",
        correct: "c",
    },
    {
        question: "What is Network Security primarily aimed at protecting?",
        a: "Only hardware components",
        b: "Client data, information, and network performance",
        c: "Email accounts only",
        d: "Only company websites",
        correct: "b",
    },
    {
        question: "What is a virus in computing?",
        a: "A hardware problem",
        b: "A malicious, downloadable file that replicates itself by changing other computer programs with its own code",
        c: "A type of legitimate software",
        d: "A network protocol",
        correct: "b",
    },
    {
        question: "According to the text on the WannaCry attack, what did experts warn about after the initial attack?",
        a: "More powerful malware would be developed",
        b: "A second wave of attacks could come",
        c: "New types of viruses would emerge",
        d: "The attackers would target different countries",
        correct: "b",
    },
    {
        question: "He's really good at _____________.",
        a: "trouble",
        b: "fault-finding",
        c: "troubleshooting",
        d: "error shooting",
        correct: "c",
    },
    {
        question: "Programmers with _____________ or licenses are not necessarily better coders.",
        a: "certified",
        b: "certifications",
        c: "papers",
        d: "degrees",
        correct: "b",
    },
    {
        question: "Which term refers to 'collections of prewritten code that users can use to optimize tasks'?",
        a: "Variables",
        b: "Constants",
        c: "Libraries",
        d: "Functions",
        correct: "c",
    },
    {
        question: "What is a 'FRAMEWORK' in programming?",
        a: "A system for keeping track of code versions",
        b: "A foundation with a specified level of complexity that may be altered by programmers",
        c: "A testing environment for new software",
        d: "A simple language with easily understood keywords and tags",
        correct: "b",
    },
    {
        question: "What is a 'FRONT END' in web development?",
        a: "The user interface of a computer or device",
        b: "The database and server side of a website",
        c: "A task performed in the background",
        d: "An algorithm for solving programming problems",
        correct: "a",
    },
    {
        question: "A website that is not _____________ makes it difficult for users to understand what to do.",
        a: "live",
        b: "user-friendly",
        c: "showing up",
        d: "font-based",
        correct: "b",
    },
    {
        question: "People find _____________ very annoying on websites.",
        a: "fonts",
        b: "colors",
        c: "pop-ups",
        d: "white spaces",
        correct: "c",
    },
    {
        question: "What is 'backend development' according to the web development terminology?",
        a: "The visual design elements of a website",
        b: "Everything that goes on behind the scenes of a website",
        c: "The mobile version of a website",
        d: "The documentation of website code",
        correct: "b",
    },
    {
        question: "In programming terminology, what's the opposite of a parent class?",
        a: "A child class",
        b: "A children's class",
        c: "A baby class",
        d: "An adult class",
        correct: "a",
    },
    {
        question: "What is 'deployment' in web development?",
        a: "The design phase of a website",
        b: "The process of going live with a website after development and testing",
        c: "Creating wireframes for a website",
        d: "Testing a website for bugs",
        correct: "b",
    },
    {
        question: "According to the web development buzzwords, what is a 'sitemap'?",
        a: "A physical map showing server locations",
        b: "An outline of all the pages on a website",
        c: "A list of all the coding languages used in a website",
        d: "A diagram showing website loading speeds",
        correct: "b",
    },
    {
        question: "What does 'SDLC' stand for in software development?",
        a: "Software Design Language Code",
        b: "System Development Life Cycle",
        c: "Software Development Life Cycle",
        d: "Standard Digital Library Computing",
        correct: "c",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}