/**
 * Datos del quiz de Inglés Técnico - Software
 * Archivo convertido al nuevo formato
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "What is software?",
        a: "The physical components of a computer",
        b: "Instructions written by a programmer which tells the computer what to do",
        c: "A type of hardware that runs programs",
        d: "A collection of wires and chips",
        correct: "b",
    },
    {
        question: "What is another term for 'programmers'?",
        a: "Software mechanics",
        b: "Code architects",
        c: "Software developers",
        d: "Computer scientists",
        correct: "c",
    },
    {
        question: "Which term is NOT commonly used to describe starting a software program?",
        a: "Execute",
        b: "Run",
        c: "Launch",
        d: "Compile",
        correct: "d",
    },
    {
        question: "What happens when software has a bug?",
        a: "It automatically fixes itself",
        b: "It may crash and terminate with a confusing message",
        c: "It always continues to run normally",
        d: "It becomes faster",
        correct: "b",
    },
    {
        question: "What might users need to do when software stops responding?",
        a: "Reinstall the operating system",
        b: "Manually abort the program",
        c: "Change the computer's hardware",
        d: "Contact the developer immediately",
        correct: "b",
    },
    {
        question: "According to the text, why should everyone studying IT learn at least one programming language?",
        a: "To become professional programmers",
        b: "To earn more money",
        c: "It forces you to think like a computer, which can be rewarding when dealing with IT-related issues",
        d: "It's a requirement for graduation",
        correct: "c",
    },
    {
        question: "What is important about software and hardware compatibility?",
        a: "Software written for Windows can run on any computer",
        b: "Software must be compatible with all components of the computer",
        c: "Hardware must adapt to any software",
        d: "Compatibility is no longer an issue with modern computers",
        correct: "b",
    },
    {
        question: "What is closed source or proprietary software?",
        a: "Software you are free to modify and improve",
        b: "Software that is not well documented",
        c: "Software you are not free to modify and improve",
        d: "Software that comes with the hardware",
        correct: "c",
    },
    {
        question: "What is an example of proprietary software mentioned in the text?",
        a: "Mozilla Firefox",
        b: "Linux",
        c: "Adobe Photoshop",
        d: "Open Office",
        correct: "c",
    },
    {
        question: "What is open source software?",
        a: "Software that is available online",
        b: "Software that is normally free to use and modify (with some restrictions)",
        c: "Software that costs less than proprietary software",
        d: "Software with the source code hidden",
        correct: "b",
    },
    {
        question: "What is an example of open source software mentioned in the text?",
        a: "Microsoft Windows",
        b: "Adobe Photoshop",
        c: "Mozilla Firefox",
        d: "Microsoft Office",
        correct: "c",
    },
    {
        question: "What is the first step mentioned for fixing a bug in open source software like Mozilla Firefox?",
        a: "Contact Mozilla",
        b: "Run a virus scan",
        c: "Download and unzip (or uncompress) the source code",
        d: "Reboot the computer",
        correct: "c",
    },
    {
        question: "What is a compiler used for in the software development process?",
        a: "To write code",
        b: "To find bugs",
        c: "To turn source code into a binary file",
        d: "To distribute software",
        correct: "c",
    },
    {
        question: "According to the text, why do programmers generally prefer open source software?",
        a: "It's cheaper",
        b: "It's faster",
        c: "Good programmers love code and want access to it",
        d: "It's easier to install",
        correct: "c",
    },
    {
        question: "What is the definition of 'abort' in the context of software?",
        a: "To upgrade a program",
        b: "To end a program or a process before its completion",
        c: "To save unsaved changes",
        d: "To restart a program",
        correct: "b",
    },
    {
        question: "What is a 'bug' in software?",
        a: "A new feature in a program",
        b: "A virus that infects a computer",
        c: "A security update",
        d: "An error or glitch in a computer program caused by a programmer's mistake",
        correct: "d",
    },
    {
        question: "What does 'closed source' mean?",
        a: "Software that is no longer supported",
        b: "Software in which the license stipulates that the user cannot see, edit, or manipulate the source code",
        c: "Software that doesn't have any bugs",
        d: "Software that works only offline",
        correct: "b",
    },
    {
        question: "What does 'compatible' mean in terms of software?",
        a: "Software that works together harmoniously",
        b: "Software that is easy to use",
        c: "Capable of being used without modification",
        d: "Software that can be customized",
        correct: "c",
    },
    {
        question: "What is a 'crash' in computing?",
        a: "When a computer physically falls down",
        b: "A computer failure which aborts an application or freezes an operating system",
        c: "When a hard drive gets full",
        d: "When multiple programs run at the same time",
        correct: "b",
    },
    {
        question: "Who is an 'end user'?",
        a: "A programmer who writes code",
        b: "A person who uses a product or service on a computer",
        c: "A technician who repairs computers",
        d: "A company that sells software",
        correct: "b",
    },
    {
        question: "What is an 'error' in computing?",
        a: "A type of software upgrade",
        b: "An incorrect action attributable to poor judgment, ignorance, or inattention",
        c: "A hardware component",
        d: "A quick fix for a bug",
        correct: "b",
    },
    {
        question: "What does it mean to 'execute' a program?",
        a: "To delete a program",
        b: "To install a program",
        c: "To start a program on a computer",
        d: "To modify a program",
        correct: "c",
    },
    {
        question: "What is a 'feature' in software?",
        a: "A bug that has been fixed",
        b: "Something a computer program is 'supposed' to do; often a reason to buy or upgrade software",
        c: "A security vulnerability",
        d: "The hardware required to run the software",
        correct: "b",
    },
    {
        question: "What does IDE stand for?",
        a: "Integrated Development Environment",
        b: "Interactive Development Engine",
        c: "Internal Debugging Experience",
        d: "Internet Developer Edition",
        correct: "a",
    },
    {
        question: "What is 'open source' software?",
        a: "Software that only works online",
        b: "A program in which the code is distributed allowing programmers to alter and change the original software",
        c: "Software that requires a license to use",
        d: "Software that is being developed and is not yet complete",
        correct: "b",
    },
    {
        question: "What is a 'programmer'?",
        a: "A person who writes or modifies software",
        b: "A person who sells software",
        c: "A person who uses software",
        d: "A person who reviews software",
        correct: "a",
    },
    {
        question: "What does 'proprietary' mean in the context of software?",
        a: "Software that is open source",
        b: "Privately developed and owned technology",
        c: "Software that is free to use",
        d: "Software that can be modified by anyone",
        correct: "b",
    },
    {
        question: "What is a 'restriction' in the context of software?",
        a: "A feature that limits the software's performance",
        b: "A rule or law which limits or controls access to something",
        c: "A requirement to run the software",
        d: "A type of software license",
        correct: "b",
    },
    {
        question: "What is 'usability' in software?",
        a: "How many features a program has",
        b: "How fast a program runs",
        c: "A measure of how easy or hard a program is to use",
        d: "How much memory a program uses",
        correct: "c",
    },
    {
        question: "According to the text, what can happen when a software program crashes?",
        a: "The user might need to press ctrl-alt-delete",
        b: "The computer's hardware gets damaged",
        c: "The user's data is automatically recovered",
        d: "The program automatically restarts",
        correct: "a",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}