/**
 * Datos del quiz de Inglés Técnico - Hardware
 * Archivo convertido al nuevo formato
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "What is the main definition of hardware?",
        a: "Programs that run on a computer",
        b: "Instructions that tell a computer what to do",
        c: "Physical parts of a computer that you can touch",
        d: "Data files containing instructions for the operating system",
        correct: "c",
    },
    {
        question: "What is the function of hardware components?",
        a: "Creating applications and performing updates",
        b: "Calculating data, storing information, processing input, and providing output",
        c: "Running software applications and operating systems",
        d: "Protecting the computer from viruses and malware",
        correct: "b",
    },
    {
        question: "What do all hardware devices include to perform their function?",
        a: "Software applications",
        b: "Internet connection",
        c: "Chips on a circuit board",
        d: "Operating system",
        correct: "c",
    },
    {
        question: "How does hardware typically interface with the rest of the computer?",
        a: "Through software protocols",
        b: "By connecting to a port, socket, or wireless radio",
        c: "Using specific applications",
        d: "Through virtual connections",
        correct: "b",
    },
    {
        question: "What is another term for internal hardware parts?",
        a: "Peripherals",
        b: "Extensions",
        c: "Components",
        d: "Accessories",
        correct: "c",
    },
    {
        question: "What is a motherboard?",
        a: "The main storage unit of a computer",
        b: "The brain of a computer that processes instructions",
        c: "The main system board that every other component connects to",
        d: "A device that converts alternating current to direct current",
        correct: "c",
    },
    {
        question: "What does a motherboard consist of?",
        a: "A large circuit board with integrated chipsets and controllers",
        b: "A series of storage devices connected together",
        c: "Multiple CPUs working together",
        d: "Software that controls hardware components",
        correct: "a",
    },
    {
        question: "What does CPU stand for?",
        a: "Computer Processing Unit",
        b: "Central Power Unit",
        c: "Central Processing Unit",
        d: "Computer Power Unit",
        correct: "c",
    },
    {
        question: "What is the function of a CPU?",
        a: "To store information permanently",
        b: "To process instructions and control the rest of the hardware",
        c: "To display graphical user interface",
        d: "To connect peripherals to the computer",
        correct: "b",
    },
    {
        question: "What is the function of RAM?",
        a: "To permanently store data",
        b: "To temporarily store information for the CPU to process",
        c: "To convert electrical current",
        d: "To display output",
        correct: "b",
    },
    {
        question: "What is the main difference between memory (RAM) and storage devices?",
        a: "RAM is external, storage devices are internal",
        b: "RAM is faster than storage devices",
        c: "RAM temporarily holds data, storage devices keep data even when powered off",
        d: "RAM is less expensive than storage devices",
        correct: "c",
    },
    {
        question: "What are examples of storage devices mentioned in the text?",
        a: "Motherboards and CPUs",
        b: "Hard drives and solid state drives",
        c: "Keyboards and mice",
        d: "Monitors and printers",
        correct: "b",
    },
    {
        question: "What is the purpose of controller cards and expansion cards?",
        a: "To convert alternating current to direct current",
        b: "To expand a computer's capabilities",
        c: "To control the operating system",
        d: "To connect external devices",
        correct: "b",
    },
    {
        question: "What are examples of expansion cards mentioned in the text?",
        a: "Motherboards and CPUs",
        b: "RAM and hard drives",
        c: "Video cards, network interfaces, and extra ports",
        d: "Monitors and keyboards",
        correct: "c",
    },
    {
        question: "What is the function of a power supply?",
        a: "To provide backup power during outages",
        b: "To convert alternating current to direct current",
        c: "To regulate power to external devices",
        d: "To cool the computer components",
        correct: "b",
    },
    {
        question: "What is the term for external hardware devices?",
        a: "Components",
        b: "Extensions",
        c: "Peripherals",
        d: "Accessories",
        correct: "c",
    },
    {
        question: "How do peripherals connect to a computer?",
        a: "Through software installations",
        b: "By one of its ports or plugs",
        c: "Through the operating system",
        d: "Via internet connection",
        correct: "b",
    },
    {
        question: "What is the purpose of monitors?",
        a: "To process data",
        b: "To store information",
        c: "To display output and provide a graphical user interface",
        d: "To input data into the computer",
        correct: "c",
    },
    {
        question: "What is the function of keyboards and mice?",
        a: "To display output",
        b: "To store data",
        c: "To process information",
        d: "To accept input from the user",
        correct: "d",
    },
    {
        question: "What do printers allow users to do?",
        a: "Enter data into the computer",
        b: "Display visual information",
        c: "Print documents onto paper",
        d: "Store information permanently",
        correct: "c",
    },
    {
        question: "What is the advantage of external storage devices over internal ones?",
        a: "They are faster",
        b: "They have more capacity",
        c: "They can be easily disconnected and reconnected to move data between computers",
        d: "They don't require drivers",
        correct: "c",
    },
    {
        question: "What must you do before installing new internal components?",
        a: "Update the operating system",
        b: "Back up all data",
        c: "Install the appropriate software",
        d: "Turn the computer off",
        correct: "d",
    },
    {
        question: "What does 'plug-and-play' refer to?",
        a: "Software that installs automatically",
        b: "External peripherals that can be connected without turning off the computer",
        c: "Gaming peripherals",
        d: "Wireless devices",
        correct: "b",
    },
    {
        question: "What are drivers?",
        a: "People who transport hardware",
        b: "Hardware components that drive the computer",
        c: "Data files containing instructions for the operating system on how to control hardware",
        d: "Software that turns the computer on",
        correct: "c",
    },
    {
        question: "Where can you typically find drivers for hardware?",
        a: "Only in computer stores",
        b: "On a disc bundled with the hardware or for download from manufacturer's website",
        c: "Inside the computer's case",
        d: "They come pre-installed on all computers",
        correct: "b",
    },
    {
        question: "What is software in relation to hardware?",
        a: "The physical components of a computer",
        b: "The programs and applications that run on a computer",
        c: "The tools used to fix hardware",
        d: "The power source for hardware",
        correct: "b",
    },
    {
        question: "Which of these is NOT mentioned as a function of hardware components?",
        a: "Calculating data",
        b: "Storing information",
        c: "Processing input",
        d: "Creating software applications",
        correct: "d",
    },
    {
        question: "What do speakers and headphones do?",
        a: "Input data into the computer",
        b: "Process audio signals",
        c: "Play sounds generated by a computer",
        d: "Store audio files",
        correct: "c",
    },
    {
        question: "What is the purpose of scanners according to the text?",
        a: "To analyze hardware issues",
        b: "To check for viruses and malware",
        c: "To create a digital copy of a document or photograph",
        d: "To display output from the computer",
        correct: "c",
    },
    {
        question: "What is a multi-function printer?",
        a: "A printer that can print in multiple colors",
        b: "A printer that combines multiple functions like printing and scanning",
        c: "A printer that can connect to multiple computers",
        d: "A printer that uses multiple types of paper",
        correct: "b",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}