/**
 * Datos del quiz de Inglés Técnico - Programación Web y Terminología
 * Archivo convertido al nuevo formato
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "We're looking for three programmers to help us develop our web-based _____________.",
        a: "applications",
        b: "appliances",
        c: "applause",
        d: "codifications",
        correct: "a",
    },
    {
        question: "You have to test the program to ensure that it works _____________.",
        a: "to expect it",
        b: "as expected",
        c: "like it expected",
        d: "with expectations",
        correct: "b",
    },
    {
        question: "Many programmers use libraries of (modifiable) code instead of _____________ from scratch.",
        a: "coding",
        b: "code",
        c: "coded",
        d: "coder",
        correct: "a",
    },
    {
        question: "Proprietary software is software that can be used _____________ by the company that develops it.",
        a: "including",
        b: "exclusively",
        c: "inclusively",
        d: "collectively",
        correct: "b",
    },
    {
        question: "Boris is going to be helping us to implement various software sub-_____________.",
        a: "parts",
        b: "pieces",
        c: "components",
        d: "sections",
        correct: "c",
    },
    {
        question: "He's really good at _____________.",
        a: "trouble",
        b: "fault-finding",
        c: "troubleshooting",
        d: "error shooting",
        correct: "c",
    },
    {
        question: "Do you have any experience with integrating internal software solutions into _____________ application software?",
        a: "third party",
        b: "second party",
        c: "first party",
        d: "fourth party",
        correct: "a",
    },
    {
        question: "Programmers with _____________ or licenses are not necessarily better coders.",
        a: "certified",
        b: "certifications",
        c: "papers",
        d: "degrees",
        correct: "b",
    },
    {
        question: "How good are you _____________ stored procedures?",
        a: "on writing",
        b: "when writing",
        c: "at writing",
        d: "for writing",
        correct: "c",
    },
    {
        question: "What's another word for 'testing'?",
        a: "debugging",
        b: "evolving",
        c: "debunking",
        d: "upgrading",
        correct: "a",
    },
    {
        question: "I don't have a lot of experience in _____________-oriented programming languages like Java.",
        a: "code",
        b: "subject",
        c: "object",
        d: "function",
        correct: "c",
    },
    {
        question: "Most of my experience is in back-_____________ programming.",
        a: "side",
        b: "end",
        c: "to-back",
        d: "office",
        correct: "b",
    },
    {
        question: "SQL is pronounced _____________.",
        a: "sequel",
        b: "scale",
        c: "school",
        d: "squeal",
        correct: "a",
    },
    {
        question: "C# is pronounced _____________.",
        a: "see sharp",
        b: "see pound",
        c: "see number",
        d: "see hash",
        correct: "a",
    },
    {
        question: "I've written 1000 lines of _____________.",
        a: "program",
        b: "coding",
        c: "code",
        d: "scripts",
        correct: "c",
    },
    {
        question: "I'm not really familiar with that programming _____________.",
        a: "language",
        b: "tongue",
        c: "lingo",
        d: "script",
        correct: "a",
    },
    {
        question: "I _____________ to work properly.",
        a: "can't get this",
        b: "can't make this",
        c: "can't fix this",
        d: "can't run this",
        correct: "a",
    },
    {
        question: "I have to install a new _____________ of the anti-virus software.",
        a: "release",
        b: "version",
        c: "layout",
        d: "revision",
        correct: "b",
    },
    {
        question: "One of your cables was _____________.",
        a: "clean",
        b: "disengaged",
        c: "unplugged",
        d: "detached",
        correct: "c",
    },
    {
        question: "Your computer is _____________ with a virus.",
        a: "sick",
        b: "infected",
        c: "infiltrated",
        d: "compromised",
        correct: "b",
    },
    {
        question: "_____________ can gather data from a user's system without the user knowing it.",
        a: "Spyware",
        b: "Software",
        c: "Shareware",
        d: "Freeware",
        correct: "a",
    },
    {
        question: "It is _____________ to download these programs.",
        a: "illegal",
        b: "illogical",
        c: "legal",
        d: "logical",
        correct: "a",
    },
    {
        question: "If you have any problems _____________ the operating system, please let me know.",
        a: "confiscating",
        b: "commending",
        c: "configuring",
        d: "conferring",
        correct: "c",
    },
    {
        question: "That program won't be able to open files with that _____________.",
        a: "extension",
        b: "expansion",
        c: "extraction",
        d: "exposition",
        correct: "a",
    },
    {
        question: "Please _____________ your computer.",
        a: "reboot",
        b: "re-initiate",
        c: "rework",
        d: "relaunch",
        correct: "a",
    },
    {
        question: "I've _____________ the problem.",
        a: "named",
        b: "identified",
        c: "inspected",
        d: "located",
        correct: "b",
    },
    {
        question: "It's not a major _____________.",
        a: "subject",
        b: "release",
        c: "issue",
        d: "problem",
        correct: "c",
    },
    {
        question: "I've been _____________ websites for the past three years.",
        a: "design",
        b: "designing",
        c: "designed",
        d: "designer",
        correct: "b",
    },
    {
        question: "I don't like the _____________ of this page.",
        a: "overview",
        b: "layer",
        c: "layout",
        d: "format",
        correct: "c",
    },
    {
        question: "If you _____________ some of the elements, it will look better.",
        a: "remake",
        b: "rearrange",
        c: "reaffirm",
        d: "rebuild",
        correct: "b",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}