/**
 * Datos del quiz de Inglés Técnico - Redes y Seguridad
 * Archivo convertido al nuevo formato
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "What is a network?",
        a: "A type of internet connection",
        b: "A group of linked computers or other devices",
        c: "A security system for computers",
        d: "A special type of server",
        correct: "b",
    },
    {
        question: "What is the difference between LANs and WANs?",
        a: "LANs use wireless connections, WANs use cables",
        b: "LANs are faster than WANs",
        c: "LANs connect computers in the same building, WANs cover larger areas",
        d: "LANs are for businesses, WANs are for homes",
        correct: "c",
    },
    {
        question: "What is a characteristic of a star network system?",
        a: "Each computer is linked to two others",
        b: "Each computer is connected to a central server",
        c: "There is a central cable called a bus",
        d: "Each computer is linked to several others",
        correct: "b",
    },
    {
        question: "What is a characteristic of a ring network system?",
        a: "Each computer is linked to two others",
        b: "Each computer is connected to a central server",
        c: "There is a central cable called a bus",
        d: "Each computer is linked to several others",
        correct: "a",
    },
    {
        question: "What is a mesh network system?",
        a: "A network where each computer is connected to a central server",
        b: "A network with a central cable",
        c: "A network where each computer is linked to two others",
        d: "A network where each computer is linked to several others",
        correct: "d",
    },
    {
        question: "What is an advantage of a mesh network?",
        a: "It's the cheapest type of network to set up",
        b: "It's the fastest type of network",
        c: "If one connection breaks, data can use other connections",
        d: "It's the easiest type of network to maintain",
        correct: "c",
    },
    {
        question: "What is the role of a server in a client-server system?",
        a: "To request data from clients",
        b: "To store data, serve websites and have other similar functions",
        c: "To encrypt data sent between computers",
        d: "To connect to the internet",
        correct: "b",
    },
    {
        question: "What does a client program do in a client-server system?",
        a: "It asks the server for data and receives data back",
        b: "It stores data and serves websites",
        c: "It manages the network connections",
        d: "It provides security for the network",
        correct: "a",
    },
    {
        question: "Which of these would typically use a LAN?",
        a: "ATMs across a city",
        b: "Home network",
        c: "Computers in police cars",
        d: "Global email system",
        correct: "b",
    },
    {
        question: "Which of these is typically a client program?",
        a: "Network operating system",
        b: "Firewall software",
        c: "Web browser",
        d: "Database management system",
        correct: "c",
    },
    {
        question: "What does VPN stand for?",
        a: "Virtual Private Network",
        b: "Very Protected Network",
        c: "Virtual Public Network",
        d: "Verified Private Network",
        correct: "a",
    },
    {
        question: "What is Network Security primarily aimed at protecting?",
        a: "Only hardware components",
        b: "Client data, information, and network performance",
        c: "Email accounts only",
        d: "Only company websites",
        correct: "b",
    },
    {
        question: "What is one benefit of a well-designed network security solution?",
        a: "It increases internet speed",
        b: "It reduces overhead expenses",
        c: "It guarantees 100% protection",
        d: "It eliminates the need for passwords",
        correct: "b",
    },
    {
        question: "What is a firewall in network security?",
        a: "Physical barrier between computers",
        b: "Software that detects viruses",
        c: "Controls incoming and outgoing traffic with predetermined security rules",
        d: "A type of secure router",
        correct: "c",
    },
    {
        question: "What is network segmentation?",
        a: "Breaking a network into smaller pieces for easier management",
        b: "Defining boundaries between network segments where assets have a common function, risk or role",
        c: "Disconnecting parts of the network for maintenance",
        d: "Connecting networks from different companies",
        correct: "b",
    },
    {
        question: "What does Access Control define?",
        a: "The speed of the network",
        b: "The type of hardware used",
        c: "The people, groups, and devices that have access to network applications and systems",
        d: "The operating system being used",
        correct: "c",
    },
    {
        question: "What is Remote Access VPN used for?",
        a: "To provide remote and secure access to a company network",
        b: "To share files between computers on the same network",
        c: "To connect multiple printers to one computer",
        d: "To increase internet speed",
        correct: "a",
    },
    {
        question: "What is the zero trust security model principle?",
        a: "Trust all users within the organization",
        b: "A user should only have the access and permissions required for their role",
        c: "Verify only external users",
        d: "Trust but verify all connections",
        correct: "b",
    },
    {
        question: "What is Email Security designed to protect?",
        a: "Only attachments",
        b: "Only sender information",
        c: "Email accounts and email content from external threats",
        d: "Only password information",
        correct: "c",
    },
    {
        question: "What does DLP stand for in network security?",
        a: "Digital Licensing Protocol",
        b: "Data Loss Prevention",
        c: "Direct Link Protection",
        d: "Database Logic Program",
        correct: "b",
    },
    {
        question: "What do Intrusion Prevention Systems (IPS) detect or prevent?",
        a: "Hardware failures",
        b: "Software updates",
        c: "Network security attacks such as brute force attacks",
        d: "Power outages",
        correct: "c",
    },
    {
        question: "What is a vulnerability in the context of network security?",
        a: "A type of malware",
        b: "A weakness in a software system",
        c: "A network monitoring tool",
        d: "A type of firewall",
        correct: "b",
    },
    {
        question: "What is sandboxing in cybersecurity?",
        a: "Disconnecting from the internet",
        b: "Running code or opening files in a safe, isolated environment",
        c: "Backing up data to a secure location",
        d: "Encrypting all files on a network",
        correct: "b",
    },
    {
        question: "What is hyperscale in network security?",
        a: "The ability of an architecture to scale appropriately as increased demand is added",
        b: "A type of security protocol",
        c: "A method of encrypting data",
        d: "A network topology",
        correct: "a",
    },
    {
        question: "What is cloud network security concerned with?",
        a: "Only physical servers",
        b: "Protecting data centers and applications hosted in cloud environments",
        c: "Only email security",
        d: "Only preventing hardware failures",
        correct: "b",
    },
    {
        question: "What does FWaaS stand for?",
        a: "File Web Access Service",
        b: "Forward Web Application Security",
        c: "Firewall-as-a-Service",
        d: "Fast Wireless Access System",
        correct: "c",
    },
    {
        question: "What does LAN stand for?",
        a: "Linked Area Network",
        b: "Local Area Network",
        c: "Local Access Node",
        d: "Large Area Network",
        correct: "b",
    },
    {
        question: "What is a bus system in networking?",
        a: "A network with multiple central servers",
        b: "A network where each computer is linked to two others",
        c: "A network with a central cable to which computers are linked",
        d: "A network that uses public transportation routes for connectivity",
        correct: "c",
    },
    {
        question: "In a client-server system, what happens when you type a web address into a browser?",
        a: "The server asks the browser for information",
        b: "The browser (client) asks the server for a web page",
        c: "The browser connects directly to another browser",
        d: "The server takes control of the client computer",
        correct: "b",
    },
    {
        question: "What is an example of a Network Security Protection mentioned in the text?",
        a: "Antivirus software",
        b: "Internet Service Provider",
        c: "Network segmentation",
        d: "Password manager",
        correct: "c",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}