/**
 * Datos del quiz de Inglés Técnico - Repaso General 1
 * Archivo de repaso con preguntas de todos los temas
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "Choose the correct definition for 'Hardware'",
        a: "The machines, wiring, and other physical components of a computer or other electronic system",
        b: "The programs and other operating information used by a computer",
        c: "A device used to put information into and get information out of the computer",
        d: "All of them are correct",
        correct: "a",
    },
    {
        question: "What does IP stand for?",
        a: "An International protocol for the transfer of compressed files.",
        b: "An Internet protocol formed by a string of numbers separated by periods between 0 and 255.",
        c: "An address used in an interconnection protocol between computer.",
        d: "All the answers are correct",
        correct: "b",
    },
    {
        question: "What does a web administrator do?",
        a: "He/she is an IT professional who develops the software code for applications",
        b: "He/she is someone who manages any kind of technological system",
        c: "He/She is responsible for all aspects of keeping website content and design fresh, backed up, and fully functional",
        d: "He/she is an executive title given to the most senior IT professional within an Enterprise",
        correct: "c",
    },
    {
        question: "What does LAN stand for?",
        a: "Linked area network",
        b: "Local Area Network",
        c: "Local Open Network",
        d: "None of them",
        correct: "b",
    },
    {
        question: "VPN stands for...",
        a: "Virtual Private Network",
        b: "Very Private Network",
        c: "Virtual Portable Network",
        d: "Virtual peripherical network",
        correct: "a",
    },
    {
        question: "The ability of finding a problem and solving it is called...",
        a: "fault-finding",
        b: "troubleshooting",
        c: "error shooting",
        d: "mistake shooting",
        correct: "b",
    },
    {
        question: "\"A block of organized, reusable code that is used to perform a single, related action.\" This refers to:",
        a: "Function",
        b: "Variable",
        c: "Constant",
        d: "Loop",
        correct: "a",
    },
    {
        question: "What is the main job description of a Hardware Engineer?",
        a: "Research, develop and test hardware or computer equipment",
        b: "Develop and operate computer systems, focus on link between hardware and software",
        c: "Develop, design and test software or construct networks and programs",
        d: "Creates the inner workings of a website",
        correct: "a",
    },
    {
        question: "What is the main definition of hardware?",
        a: "Programs that run on a computer",
        b: "Instructions that tell a computer what to do",
        c: "Physical parts of a computer that you can touch",
        d: "Data files containing instructions for the operating system",
        correct: "c",
    },
    {
        question: "What is the function of RAM?",
        a: "To permanently store data",
        b: "To temporarily store information for the CPU to process",
        c: "To convert electrical current",
        d: "To display output",
        correct: "b",
    },
    {
        question: "What is software?",
        a: "The physical components of a computer",
        b: "Instructions written by a programmer which tells the computer what to do",
        c: "A type of hardware that runs programs",
        d: "A collection of wires and chips",
        correct: "b",
    },
    {
        question: "What is a 'bug' in software?",
        a: "A new feature in a program",
        b: "A virus that infects a computer",
        c: "A security update",
        d: "An error or glitch in a computer program caused by a programmer's mistake",
        correct: "d",
    },
    {
        question: "What is a dedicated server?",
        a: "A server with multiple users",
        b: "A single computer exclusively reserved for hosting a website",
        c: "A virtual machine",
        d: "A network of computers",
        correct: "b",
    },
    {
        question: "What does 'bandwidth' in web hosting refer to?",
        a: "The physical space on a server",
        b: "The number of websites on a server",
        c: "The speed of a server's processor",
        d: "Data transfer capacity",
        correct: "d",
    },
    {
        question: "What is a network?",
        a: "A type of internet connection",
        b: "A group of linked computers or other devices",
        c: "A security system for computers",
        d: "A special type of server",
        correct: "b",
    },
    {
        question: "What is a characteristic of a mesh network system?",
        a: "A network where each computer is connected to a central server",
        b: "A network with a central cable",
        c: "A network where each computer is linked to two others",
        d: "A network where each computer is linked to several others",
        correct: "d",
    },
    {
        question: "What is malware?",
        a: "Software programs intended to harm or exploit computer systems",
        b: "Software programs that protect computer systems from viruses",
        c: "Software programs used for data analysis",
        d: "Software programs that help in creating websites",
        correct: "a",
    },
    {
        question: "What is the main purpose of ransomware?",
        a: "To gain access to sensitive information",
        b: "To gain money by encrypting data and demanding payment for its release",
        c: "To improve network speed",
        d: "To prevent unauthorized access",
        correct: "b",
    },
    {
        question: "We're looking for three programmers to help us develop our web-based _____________.",
        a: "applications",
        b: "appliances",
        c: "applause",
        d: "codifications",
        correct: "a",
    },
    {
        question: "Many programmers use libraries of (modifiable) code instead of _____________ from scratch.",
        a: "coding",
        b: "code",
        c: "coded",
        d: "coder",
        correct: "a",
    },
    {
        question: "What does 'LOOP' refer to in programming?",
        a: "A component that keeps track of time",
        b: "A sequence of instructions that repeat until a condition is met",
        c: "A location that stores temporary data",
        d: "A process of creating an executable program",
        correct: "b",
    },
    {
        question: "What is a 'VARIABLE' in programming terms?",
        a: "A permanent value that never changes",
        b: "A location that stores temporary data which can be modified",
        c: "A system for organizing code repositories",
        d: "A type of software license",
        correct: "b",
    },
    {
        question: "When a website is full of information with few white spaces, we say it is...",
        a: "Buggy",
        b: "Cluttered",
        c: "Efficient",
        d: "User-friendly",
        correct: "b",
    },
    {
        question: "Instead of creating a long page that requires extensive _____________, you should break it up into multiple pages.",
        a: "scrolling",
        b: "clicking",
        c: "playing",
        d: "reading",
        correct: "a",
    },
    {
        question: "Choose the best definition for Trojan:",
        a: "A trojan is a backdoor program that creates an entryway for malicious users to access the computer system by using what looks like a real program, but quickly turns out to be harmful.",
        b: "It is s a computer virus that gathers information about a person or organization without their express knowledge and may send the information gathered to a third party without the consumer's consent",
        c: "Can slow down computer networks by eating up bandwidth as well as the slow the efficiency of your computer to process data.",
        d: "Can redirect your search requests to advertising websites and collect marketing data about you",
        correct: "a",
    },
    {
        question: "Choose the correct definition for \"LOOP\"",
        a: "the user interface of a computer or any device",
        b: "a sequence of instructions that repeat the same process over and over until a condition is met and it receives the order to stop",
        c: "collections of prewritten code that users can use to optimize tasks.",
        d: "a set of rules, routines, and protocols to build software applications.",
        correct: "b",
    },
    {
        question: "What is spyware designed to do?",
        a: "Improves computer performance",
        b: "Gathers information about a person or organization without their express knowledge",
        c: "Helps protect against other malware",
        d: "Encrypts files for security purposes",
        correct: "b",
    },
    {
        question: "What is a 'backdoor' in the context of malware?",
        a: "To provide unauthorized access to a computer system",
        b: "To monitor and capture sensitive information",
        c: "To replicate itself and spread to other computers",
        d: "To display unwanted advertisements",
        correct: "a",
    },
    {
        question: "What does 'responsive design' ensure?",
        a: "That a website loads quickly",
        b: "That a website is displayed correctly on different devices and screen sizes",
        c: "That a website has many interactive elements",
        d: "That a website is available 24/7",
        correct: "b",
    },
    {
        question: "What is 'Git' in web development terminology?",
        a: "A programming language",
        b: "A version control system where developers can store and manage code",
        c: "A type of web browser",
        d: "A website hosting service",
        correct: "b",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}