/**
 * Datos del quiz de Inglés Técnico - Desarrollo Web y Términos de Programación
 * Archivo convertido al nuevo formato
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "What does 'LOOP' refer to in programming?",
        a: "A component that keeps track of time",
        b: "A sequence of instructions that repeat until a condition is met",
        c: "A location that stores temporary data",
        d: "A process of creating an executable program",
        correct: "b",
    },
    {
        question: "Which of these best describes a 'FUNCTION' in programming?",
        a: "A block of organized, reusable code that performs a single, related action",
        b: "A value that should not be altered during normal execution",
        c: "A method for storing multiple data types",
        d: "A format for displaying content on a webpage",
        correct: "a",
    },
    {
        question: "What is a 'VARIABLE' in programming terms?",
        a: "A permanent value that never changes",
        b: "A location that stores temporary data which can be modified",
        c: "A system for organizing code repositories",
        d: "A type of software license",
        correct: "b",
    },
    {
        question: "Which term refers to 'collections of prewritten code that users can use to optimize tasks'?",
        a: "Variables",
        b: "Constants",
        c: "Libraries",
        d: "Functions",
        correct: "c",
    },
    {
        question: "What is a 'FRAMEWORK' in programming?",
        a: "A system for keeping track of code versions",
        b: "A foundation with a specified level of complexity that may be altered by programmers",
        c: "A testing environment for new software",
        d: "A simple language with easily understood keywords and tags",
        correct: "b",
    },
    {
        question: "What process creates an executable program through code written in a compiled programming language?",
        a: "Debugging",
        b: "Compilation",
        c: "Optimization",
        d: "Tokenization",
        correct: "b",
    },
    {
        question: "What is a 'FRONT END' in web development?",
        a: "The user interface of a computer or device",
        b: "The database and server side of a website",
        c: "A task performed in the background",
        d: "An algorithm for solving programming problems",
        correct: "a",
    },
    {
        question: "What is an 'API' in programming?",
        a: "A physical part of the computer hardware",
        b: "A relatively simple language with understood keywords",
        c: "A set of rules, routines, and protocols to build software applications",
        d: "A set of instructions designed to solve a specific problem",
        correct: "c",
    },
    {
        question: "Which term describes 'a set of instructions or rules designed to solve a definite problem'?",
        a: "Function",
        b: "Variable",
        c: "Algorithm",
        d: "Token",
        correct: "c",
    },
    {
        question: "When a website is full of information with few white spaces, we say it is...",
        a: "Buggy",
        b: "Cluttered",
        c: "Efficient",
        d: "User-friendly",
        correct: "b",
    },
    {
        question: "What does making headers 'stand out' mean in web design?",
        a: "Making them less visible",
        b: "Making them more prominent and noticeable",
        c: "Removing them entirely",
        d: "Rearranging their position",
        correct: "b",
    },
    {
        question: "A website that is not _____________ makes it difficult for users to understand what to do.",
        a: "live",
        b: "user-friendly",
        c: "showing up",
        d: "font-based",
        correct: "b",
    },
    {
        question: "Instead of creating a long page that requires extensive _____________, you should break it up into multiple pages.",
        a: "scrolling",
        b: "clicking",
        c: "playing",
        d: "reading",
        correct: "a",
    },
    {
        question: "People find _____________ very annoying on websites.",
        a: "fonts",
        b: "colors",
        c: "pop-ups",
        d: "white spaces",
        correct: "c",
    },
    {
        question: "When images are not _____________ on a website, it means they are not being displayed properly.",
        a: "showing up",
        b: "clearing",
        c: "arranging",
        d: "clicking",
        correct: "a",
    },
    {
        question: "Based on the web developer article, what does 'bootstrap' refer to?",
        a: "A device for restarting computers",
        b: "A free, open-source frontend framework for designing websites",
        c: "A type of computer virus",
        d: "A method for testing software",
        correct: "b",
    },
    {
        question: "What is 'backend development' according to the web development terminology?",
        a: "The visual design elements of a website",
        b: "Everything that goes on behind the scenes of a website",
        c: "The mobile version of a website",
        d: "The documentation of website code",
        correct: "b",
    },
    {
        question: "According to the web development terminology, what is a 'bug'?",
        a: "A new feature in a website",
        b: "An error that prevents a website or app from running correctly",
        c: "A small image on a webpage",
        d: "A type of software license",
        correct: "b",
    },
    {
        question: "The web development article defines 'cache' as:",
        a: "A type of computer memory",
        b: "A temporary storage space for data",
        c: "A programming language",
        d: "A type of website security",
        correct: "b",
    },
    {
        question: "What is the correct definition of CSS according to the web development terms?",
        a: "Computer Style System",
        b: "Cascading Style Sheets - a markup language for visual elements",
        c: "Code Syntax Structure",
        d: "Customer Service Support",
        correct: "b",
    },
    {
        question: "According to the programming vocabulary document, Class A did not _____________ the variables from class B.",
        a: "inherent",
        b: "inherit",
        c: "inhibit",
        d: "inhebit",
        correct: "b",
    },
    {
        question: "In programming terminology, what's the opposite of a parent class?",
        a: "A child class",
        b: "A children's class",
        c: "A baby class",
        d: "An adult class",
        correct: "a",
    },
    {
        question: "What is the process of naming a variable called in programming?",
        a: "Variable christening",
        b: "Variable declaration",
        c: "Variable calling",
        d: "Variable labeling",
        correct: "b",
    },
    {
        question: "What do you do with a function in programming?",
        a: "You call out to it",
        b: "You call it",
        c: "You call up on it",
        d: "You name it",
        correct: "b",
    },
    {
        question: "In web development, what does 'debugging' refer to?",
        a: "Adding insects to a website theme",
        b: "The process of identifying and fixing bugs or errors",
        c: "Creating new website features",
        d: "The beta testing phase of development",
        correct: "b",
    },
    {
        question: "What is 'deployment' in web development?",
        a: "The design phase of a website",
        b: "The process of going live with a website after development and testing",
        c: "Creating wireframes for a website",
        d: "Testing a website for bugs",
        correct: "b",
    },
    {
        question: "What does 'responsive design' ensure?",
        a: "That a website loads quickly",
        b: "That a website is displayed correctly on different devices and screen sizes",
        c: "That a website has many interactive elements",
        d: "That a website is available 24/7",
        correct: "b",
    },
    {
        question: "According to the web development buzzwords, what is a 'sitemap'?",
        a: "A physical map showing server locations",
        b: "An outline of all the pages on a website",
        c: "A list of all the coding languages used in a website",
        d: "A diagram showing website loading speeds",
        correct: "b",
    },
    {
        question: "What is 'Git' in web development terminology?",
        a: "A programming language",
        b: "A version control system where developers can store and manage code",
        c: "A type of web browser",
        d: "A website hosting service",
        correct: "b",
    },
    {
        question: "What does 'SDLC' stand for in software development?",
        a: "Software Design Language Code",
        b: "System Development Life Cycle",
        c: "Software Development Life Cycle",
        d: "Standard Digital Library Computing",
        correct: "c",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}