/**
 * Datos del quiz de Inglés Técnico - Malware y Seguridad
 * Archivo convertido al nuevo formato
 */

// Definir los datos del quiz
const quizQuestions = [
    {
        question: "What is malware?",
        a: "Software programs intended to harm or exploit computer systems",
        b: "Software programs that protect computer systems from viruses",
        c: "Software programs used for data analysis",
        d: "Software programs that help in creating websites",
        correct: "a",
    },
    {
        question: "Which of the following is NOT a type of malware?",
        a: "Virus",
        b: "Worm",
        c: "Firewall",
        d: "Trojan",
        correct: "c",
    },
    {
        question: "What is a virus in computing?",
        a: "A hardware problem",
        b: "A malicious, downloadable file that replicates itself by changing other computer programs with its own code",
        c: "A type of legitimate software",
        d: "A network protocol",
        correct: "b",
    },
    {
        question: "What is a key characteristic of worms?",
        a: "They slow down computer networks by eating up bandwidth",
        b: "They need human interaction to spread",
        c: "They cannot function without a host program",
        d: "They always attack hardware components",
        correct: "a",
    },
    {
        question: "What is a Trojan in computing?",
        a: "A type of computer hardware",
        b: "A legitimate software program",
        c: "A backdoor program that creates an entryway for malicious users by looking like a real program",
        d: "A network security tool",
        correct: "c",
    },
    {
        question: "What does spyware do?",
        a: "Improves computer performance",
        b: "Gathers information about a person or organization without their express knowledge",
        c: "Helps protect against other malware",
        d: "Encrypts files for security purposes",
        correct: "b",
    },
    {
        question: "What is adware designed to do?",
        a: "Improve system security",
        b: "Enhance web browsing",
        c: "Redirect search requests to advertising websites and collect marketing data",
        d: "Create system backups",
        correct: "c",
    },
    {
        question: "What is the main purpose of ransomware?",
        a: "To gain access to sensitive information",
        b: "To gain money by encrypting data and demanding payment for its release",
        c: "To improve network speed",
        d: "To prevent unauthorized access",
        correct: "b",
    },
    {
        question: "According to the text, what is the difference between a virus and a worm?",
        a: "A virus is more dangerous than a worm",
        b: "A worm needs a host program to spread, a virus doesn't",
        c: "A virus needs a host program to spread, a worm can work independently",
        d: "There is no difference",
        correct: "c",
    },
    {
        question: "What company was angry with America's National Security Agency regarding the WannaCry ransomware?",
        a: "Google",
        b: "Apple",
        c: "Microsoft",
        d: "Facebook",
        correct: "c",
    },
    {
        question: "According to the WannaCry article, why did Microsoft's president say the attack happened?",
        a: "Because of poor software development",
        b: "Because of weak passwords",
        c: "Because the NSA keeps lots of cyber-weapons on its computers",
        d: "Because users didn't update their software",
        correct: "c",
    },
    {
        question: "What did Brad Smith compare the storing of cyber-weapons to?",
        a: "Building nuclear weapons",
        b: "Creating dangerous chemicals",
        c: "Stealing missiles from the USA",
        d: "Hacking government computers",
        correct: "c",
    },
    {
        question: "How many computers did WannaCry affect according to Europol?",
        a: "100,000",
        b: "150,000",
        c: "200,000",
        d: "250,000",
        correct: "c",
    },
    {
        question: "What organization in the UK was particularly affected by WannaCry?",
        a: "The banking system",
        b: "Universities",
        c: "The National Health Service",
        d: "The government websites",
        correct: "c",
    },
    {
        question: "What did experts warn people to do after the WannaCry attack?",
        a: "Update their operating systems",
        b: "Change their passwords",
        c: "Back up their files",
        d: "Buy antivirus software",
        correct: "c",
    },
    {
        question: "What is a keylogger primarily used for?",
        a: "To record and capture a user's keystrokes and login credentials",
        b: "To remove malicious software",
        c: "To display unwanted advertisements",
        d: "To encrypt data",
        correct: "a",
    },
    {
        question: "What is the main purpose of a backdoor in the context of malware?",
        a: "To provide unauthorized access to a computer system",
        b: "To monitor and capture sensitive information",
        c: "To replicate itself and spread to other computers",
        d: "To display unwanted advertisements",
        correct: "a",
    },
    {
        question: "When you pay the creator of ransomware that currently infects your computer, are you guaranteed to get your computer back?",
        a: "Yes, all ransomware creators provide a decryption key after payment",
        b: "No, there is no guarantee you will regain access after payment",
        c: "Yes, but only if you pay within the first 24 hours",
        d: "It depends on the type of ransomware",
        correct: "b",
    },
    {
        question: "What do websites use to verify users as human and prevent malicious bot attacks?",
        a: "Cookies",
        b: "CAPTCHA",
        c: "URLs",
        d: "Firewalls",
        correct: "b",
    },
    {
        question: "Which malicious program cannot do anything until actions are taken to activate the attached file?",
        a: "Trojan Horse",
        b: "Worm",
        c: "Virus",
        d: "Bot",
        correct: "c",
    },
    {
        question: "Can worms spread and harm independently?",
        a: "Yes, worms can spread without a host program",
        b: "No, worms need human interaction to spread",
        c: "No, worms need a host program like viruses",
        d: "Only certain types of worms can spread independently",
        correct: "a",
    },
    {
        question: "What is the NSA according to the text?",
        a: "A software company",
        b: "A hacking group",
        c: "America's military intelligence organization",
        d: "A network security company",
        correct: "c",
    },
    {
        question: "What is a 'ransom' in the context of ransomware?",
        a: "A type of encryption",
        b: "Money demanded to regain access to a computer or data",
        c: "A security certificate",
        d: "A backup system",
        correct: "b",
    },
    {
        question: "Which of the following best describes what happened during the WannaCry attack?",
        a: "Personal data was stolen and published online",
        b: "Computer systems were shut down and a ransom was demanded",
        c: "Websites were defaced with political messages",
        d: "Email accounts were hacked to send spam",
        correct: "b",
    },
    {
        question: "According to the text, what tools did the WannaCry ransomware use?",
        a: "Custom tools developed by hackers",
        b: "Computer spying tools originally designed by the NSA",
        c: "Commercial security tools",
        d: "Open-source hacking tools",
        correct: "b",
    },
    {
        question: "What happens when a user's system is infected with ransomware?",
        a: "The system slows down but continues to function",
        b: "The system is blocked until the owner pays money to the hackers",
        c: "The system automatically formats all drives",
        d: "The system sends all data to the hackers",
        correct: "b",
    },
    {
        question: "What operation was affected in the UK due to the WannaCry attack?",
        a: "Public transportation",
        b: "Banking services",
        c: "Many operations in the National Health Service",
        d: "University admissions",
        correct: "c",
    },
    {
        question: "According to the text on the WannaCry attack, what did experts warn about after the initial attack?",
        a: "More powerful malware would be developed",
        b: "A second wave of attacks could come",
        c: "New types of viruses would emerge",
        d: "The attackers would target different countries",
        correct: "b",
    },
    {
        question: "What synonym for 'angry' is mentioned in the WannaCry article?",
        a: "Upset",
        b: "Mad",
        c: "Furious",
        d: "Irritated",
        correct: "c",
    },
    {
        question: "What synonym for 'harmful' is mentioned in the WannaCry article?",
        a: "Dangerous",
        b: "Malicious",
        c: "Risky",
        d: "Deadly",
        correct: "a",
    }
];

// Inicializar el quiz con los datos
if (typeof initializeQuiz === 'function') {
    initializeQuiz(quizQuestions);
} else {
    console.error("Error: El motor del quiz no está cargado correctamente");
}